/* ============================================================================
   VOCAB_DATA — Banque de vocabulaire français DELF/DALF (module 百词斩)
   Format conforme au brief §6.3. Contenu 100 % hors-ligne.
   « image » = emoji (association visuelle façon 百词斩, sans pipeline d'images).
   Chaque mot : traduction 中文 + anglais (apprenants anglophones), IPA, emoji,
   DEUX exemples (fr / 中 / en), collocations et notes.
   ========================================================================== */
(function(){
  "use strict";
  // ex1 / ex2 = [phrase_fr, traduction_zh, traduction_en]
  function w(id,level,word,pos,pos_zh,gender,ipa,emoji,zh,en,ex1,ex2,coll,notes){
    return {id:id,level:level,word:word,pos:pos,pos_zh:pos_zh,gender:gender,ipa:ipa,emoji:emoji,
      zh:zh,en:en||[],
      ex_fr:ex1[0],ex_zh:ex1[1],ex_en:ex1[2],
      ex2_fr:ex2?ex2[0]:"",ex2_zh:ex2?ex2[1]:"",ex2_en:ex2?ex2[2]:"",
      coll:coll||[],notes:notes||""};
  }
  var L1="DELF_B1", L2="DELF_B2", L3="DALF_C1", L4="DALF_C2";
  var WORDS=[
    /* ---------------- DELF B1 : quotidien, voyages, travail, sentiments ---------------- */
    w("b1_001",L1,"améliorer","v.","动词",null,"[ameljɔʁe]","📈",["改善","提高"],["to improve"],
      ["Je voudrais améliorer mon niveau de français.","我想提高我的法语水平。","I'd like to improve my level of French."],
      ["Ces exercices aident à améliorer la prononciation.","这些练习有助于改善发音。","These exercises help improve pronunciation."],
      [{fr:"améliorer la qualité",zh:"提高质量"}],"注意区分 « améliorer »（改善某物）和 « s'améliorer »（自身变好）。"),
    w("b1_002",L1,"voyage","n.m.","阳性名词","m","[vwajaʒ]","🧳",["旅行","旅程"],["trip","journey"],
      ["Nous préparons un voyage en Italie.","我们在准备一次去意大利的旅行。","We're planning a trip to Italy."],
      ["Le voyage en train a duré six heures.","火车旅程持续了六个小时。","The train journey lasted six hours."],
      [{fr:"partir en voyage",zh:"去旅行"}],""),
    w("b1_003",L1,"quotidien","adj.","形容词",null,"[kɔtidjɛ̃]","📅",["日常的","每天的"],["daily","everyday"],
      ["La vie quotidienne à Paris est chère.","巴黎的日常生活很贵。","Daily life in Paris is expensive."],
      ["Il fait du sport de façon quotidienne.","他每天都运动。","He exercises on a daily basis."],
      [{fr:"la vie quotidienne",zh:"日常生活"}],""),
    w("b1_004",L1,"réussir","v.","动词",null,"[ʁeysiʁ]","🏆",["成功","考取"],["to succeed","to pass"],
      ["Elle a réussi son examen.","她考试通过了。","She passed her exam."],
      ["Avec du travail, tu vas réussir.","只要努力，你会成功的。","With hard work, you'll succeed."],
      [{fr:"réussir un examen",zh:"通过考试"}],""),
    w("b1_005",L1,"inquiet","adj.","形容词",null,"[ɛ̃kjɛ]","😟",["担心的","不安的"],["worried","anxious"],
      ["Je suis inquiet pour mon avenir.","我为我的未来感到担心。","I'm worried about my future."],
      ["Sa mère est inquiète quand il rentre tard.","他晚归时母亲会担心。","His mother gets worried when he comes home late."],
      [{fr:"être inquiet",zh:"感到担心"}],"阴性形式为 « inquiète »。"),
    w("b1_006",L1,"souvenir","n.m.","阳性名词","m","[suvniʁ]","📸",["回忆","纪念品"],["memory","souvenir"],
      ["J'ai de bons souvenirs de ce voyage.","我对这次旅行有美好的回忆。","I have good memories of that trip."],
      ["Elle a rapporté un souvenir de Rome.","她从罗马带回了一件纪念品。","She brought back a souvenir from Rome."],
      [{fr:"garder un souvenir",zh:"留下回忆"}],""),
    w("b1_007",L1,"entreprise","n.f.","阴性名词","f","[ɑ̃tʁəpʁiz]","🏢",["公司","企业"],["company","business"],
      ["Il travaille dans une grande entreprise.","他在一家大公司工作。","He works in a big company."],
      ["Elle a créé son entreprise à trente ans.","她三十岁时创办了自己的公司。","She started her own business at thirty."],
      [{fr:"créer une entreprise",zh:"创办公司"}],""),
    w("b1_008",L1,"conseil","n.m.","阳性名词","m","[kɔ̃sɛj]","💡",["建议","忠告"],["advice","piece of advice"],
      ["Merci pour tes conseils.","谢谢你的建议。","Thanks for your advice."],
      ["Le médecin m'a donné un bon conseil.","医生给了我一个很好的建议。","The doctor gave me a good piece of advice."],
      [{fr:"donner un conseil",zh:"给建议"}],""),
    w("b1_009",L1,"emprunter","v.","动词",null,"[ɑ̃pʁœ̃te]","🔁",["借入","借用"],["to borrow"],
      ["Je peux emprunter ton stylo ?","我能借用你的笔吗？","Can I borrow your pen?"],
      ["Il a emprunté un livre à la bibliothèque.","他从图书馆借了一本书。","He borrowed a book from the library."],
      [{fr:"emprunter de l'argent",zh:"借钱"}],"« emprunter »（借入）≠ « prêter »（借出）。"),
    w("b1_010",L1,"gentil","adj.","形容词",null,"[ʒɑ̃ti]","😊",["善良的","友好的"],["kind","nice"],
      ["Ta voisine est très gentille.","你的邻居非常友好。","Your neighbour is very kind."],
      ["C'est gentil de m'aider.","你帮我真好。","It's kind of you to help me."],
      [{fr:"être gentil avec",zh:"对…友好"}],""),
    w("b1_011",L1,"santé","n.f.","阴性名词","f","[sɑ̃te]","🩺",["健康"],["health"],
      ["La santé est plus importante que l'argent.","健康比金钱更重要。","Health is more important than money."],
      ["Le sport est bon pour la santé.","运动有益健康。","Exercise is good for your health."],
      [{fr:"être en bonne santé",zh:"身体健康"}],""),
    w("b1_012",L1,"décider","v.","动词",null,"[deside]","✅",["决定"],["to decide"],
      ["Nous avons décidé de partir demain.","我们决定明天出发。","We've decided to leave tomorrow."],
      ["C'est à toi de décider.","由你来决定。","It's up to you to decide."],
      [{fr:"décider de faire",zh:"决定做某事"}],""),
    w("b1_013",L1,"météo","n.f.","阴性名词","f","[meteo]","🌦️",["天气预报","天气"],["weather","weather forecast"],
      ["La météo annonce de la pluie.","天气预报说要下雨。","The forecast says it will rain."],
      ["On regarde la météo avant de partir.","出发前我们看看天气预报。","We check the weather before leaving."],
      [{fr:"regarder la météo",zh:"看天气预报"}],""),
    w("b1_014",L1,"cuisine","n.f.","阴性名词","f","[kɥizin]","🍳",["厨房","烹饪"],["kitchen","cooking","cuisine"],
      ["J'adore la cuisine française.","我很喜欢法国菜。","I love French cuisine."],
      ["Elle prépare le dîner dans la cuisine.","她在厨房里准备晚饭。","She's making dinner in the kitchen."],
      [{fr:"faire la cuisine",zh:"做饭"}],""),
    w("b1_015",L1,"fatigué","adj.","形容词",null,"[fatiɡe]","😴",["疲惫的","累的"],["tired"],
      ["Je suis très fatigué ce soir.","我今晚很累。","I'm very tired tonight."],
      ["Après la course, il était fatigué.","跑步之后他很累。","After the run, he was tired."],
      [{fr:"se sentir fatigué",zh:"感到疲惫"}],""),
    w("b1_016",L1,"argent","n.m.","阳性名词","m","[aʁʒɑ̃]","💰",["钱","银"],["money","silver"],
      ["Je n'ai pas assez d'argent.","我的钱不够。","I don't have enough money."],
      ["Il gagne bien son argent.","他挣钱不少。","He earns good money."],
      [{fr:"gagner de l'argent",zh:"赚钱"}],""),
    w("b1_017",L1,"rencontrer","v.","动词",null,"[ʁɑ̃kɔ̃tʁe]","🤝",["遇见","结识"],["to meet"],
      ["J'ai rencontré un ami en ville.","我在城里遇见了一个朋友。","I met a friend in town."],
      ["Ils se sont rencontrés à l'université.","他们在大学里相识。","They met at university."],
      [{fr:"rencontrer quelqu'un",zh:"遇见某人"}],""),
    w("b1_018",L1,"heureux","adj.","形容词",null,"[œʁø]","😄",["幸福的","高兴的"],["happy"],
      ["Ils sont heureux ensemble.","他们在一起很幸福。","They're happy together."],
      ["Je suis heureux de vous rencontrer.","很高兴认识您。","I'm happy to meet you."],
      [{fr:"rendre heureux",zh:"使…幸福"}],"阴性形式为 « heureuse »。"),
    w("b1_019",L1,"gare","n.f.","阴性名词","f","[ɡaʁ]","🚉",["火车站"],["(train) station"],
      ["Le train part de la gare à midi.","火车中午从车站出发。","The train leaves the station at noon."],
      ["On se retrouve devant la gare.","我们在火车站前碰面。","Let's meet in front of the station."],
      [{fr:"aller à la gare",zh:"去火车站"}],""),
    w("b1_020",L1,"projet","n.m.","阳性名词","m","[pʁɔʒɛ]","📋",["计划","项目"],["project","plan"],
      ["Elle a un projet intéressant.","她有一个有趣的计划。","She has an interesting project."],
      ["Nous avons des projets pour cet été.","我们对今年夏天有一些计划。","We have plans for this summer."],
      [{fr:"réaliser un projet",zh:"实现计划"}],""),
    w("b1_021",L1,"oublier","v.","动词",null,"[ublije]","🤦",["忘记"],["to forget"],
      ["N'oublie pas ton passeport !","别忘了你的护照！","Don't forget your passport!"],
      ["J'ai oublié son nom.","我忘了他的名字。","I've forgotten his name."],
      [{fr:"oublier de faire",zh:"忘了做某事"}],""),
    w("b1_022",L1,"cadeau","n.m.","阳性名词","m","[kado]","🎁",["礼物"],["gift","present"],
      ["C'est un cadeau pour toi.","这是给你的礼物。","It's a present for you."],
      ["Ils offrent des cadeaux à Noël.","他们在圣诞节送礼物。","They give gifts at Christmas."],
      [{fr:"offrir un cadeau",zh:"送礼物"}],"复数为 « cadeaux »。"),
    w("b1_023",L1,"content","adj.","形容词",null,"[kɔ̃tɑ̃]","🙂",["满意的","高兴的"],["glad","pleased"],
      ["Je suis content de te voir.","见到你我很高兴。","I'm glad to see you."],
      ["Elle est contente de son travail.","她对自己的工作很满意。","She's pleased with her work."],
      [{fr:"être content de",zh:"对…满意"}],""),
    w("b1_024",L1,"voisin","n.m.","阳性名词","m","[vwazɛ̃]","🏠",["邻居"],["neighbour"],
      ["Mon voisin est musicien.","我的邻居是音乐家。","My neighbour is a musician."],
      ["Nous invitons les voisins ce soir.","我们今晚邀请邻居。","We're inviting the neighbours tonight."],
      [{fr:"un bon voisin",zh:"好邻居"}],""),

    /* ---------------- DELF B2 : argumentation, société, environnement ---------------- */
    w("b2_001",L2,"environnement","n.m.","阳性名词","m","[ɑ̃viʁɔnmɑ̃]","🌍",["环境"],["environment"],
      ["Il faut protéger l'environnement.","必须保护环境。","We must protect the environment."],
      ["La pollution nuit à l'environnement.","污染损害环境。","Pollution harms the environment."],
      [{fr:"protéger l'environnement",zh:"保护环境"}],""),
    w("b2_002",L2,"pollution","n.f.","阴性名词","f","[pɔlysjɔ̃]","🏭",["污染"],["pollution"],
      ["La pollution de l'air augmente en ville.","城市里的空气污染在加剧。","Air pollution is increasing in the city."],
      ["La ville lutte contre la pollution.","这座城市在治理污染。","The city is fighting pollution."],
      [{fr:"réduire la pollution",zh:"减少污染"}],""),
    w("b2_003",L2,"chômage","n.m.","阳性名词","m","[ʃomaʒ]","📉",["失业"],["unemployment"],
      ["Le taux de chômage a baissé.","失业率下降了。","The unemployment rate has fallen."],
      ["Il est au chômage depuis six mois.","他失业已经六个月了。","He has been unemployed for six months."],
      [{fr:"lutter contre le chômage",zh:"应对失业"}],""),
    w("b2_004",L2,"citoyen","n.m.","阳性名词","m","[sitwajɛ̃]","🗳️",["公民"],["citizen"],
      ["Chaque citoyen a des droits.","每个公民都有权利。","Every citizen has rights."],
      ["Les citoyens votent dimanche.","公民们星期天投票。","Citizens vote on Sunday."],
      [{fr:"un citoyen responsable",zh:"负责任的公民"}],""),
    w("b2_005",L2,"débat","n.m.","阳性名词","m","[deba]","💬",["辩论","讨论"],["debate"],
      ["Le débat sur l'école continue.","关于学校的辩论仍在继续。","The debate about schools continues."],
      ["Le sujet a lancé un vif débat.","这个话题引发了激烈辩论。","The topic sparked a lively debate."],
      [{fr:"lancer un débat",zh:"发起讨论"}],""),
    w("b2_006",L2,"inégalité","n.f.","阴性名词","f","[inegalite]","⚖️",["不平等"],["inequality"],
      ["Les inégalités sociales se creusent.","社会不平等在加剧。","Social inequalities are widening."],
      ["L'école doit réduire les inégalités.","学校应当缩小不平等。","Schools should reduce inequalities."],
      [{fr:"réduire les inégalités",zh:"缩小不平等"}],""),
    w("b2_007",L2,"développer","v.","动词",null,"[devlɔpe]","🚀",["发展","开发"],["to develop"],
      ["L'entreprise veut développer ses activités.","公司想发展业务。","The company wants to develop its business."],
      ["Il faut développer votre argument.","你需要展开你的论点。","You need to develop your argument."],
      [{fr:"développer une idée",zh:"展开论述"}],""),
    w("b2_008",L2,"conséquence","n.f.","阴性名词","f","[kɔ̃sekɑ̃s]","➡️",["后果","结果"],["consequence"],
      ["Cette décision a de lourdes conséquences.","这个决定有严重后果。","This decision has serious consequences."],
      ["Il n'a pas mesuré les conséquences de son acte.","他没有意识到自己行为的后果。","He didn't realise the consequences of his action."],
      [{fr:"avoir des conséquences",zh:"产生后果"}],""),
    w("b2_009",L2,"nuisible","adj.","形容词",null,"[nɥizibl]","☠️",["有害的"],["harmful"],
      ["Le tabac est nuisible à la santé.","烟草对健康有害。","Tobacco is harmful to health."],
      ["Ces produits sont nuisibles pour l'environnement.","这些产品对环境有害。","These products are harmful to the environment."],
      [{fr:"nuisible à",zh:"对…有害"}],""),
    w("b2_010",L2,"gaspillage","n.m.","阳性名词","m","[ɡaspijaʒ]","🗑️",["浪费"],["waste"],
      ["Le gaspillage alimentaire est un problème.","食物浪费是个问题。","Food waste is a problem."],
      ["Réduire le gaspillage d'eau est essentiel.","减少水的浪费至关重要。","Reducing water waste is essential."],
      [{fr:"lutter contre le gaspillage",zh:"反对浪费"}],""),
    w("b2_011",L2,"favoriser","v.","动词",null,"[favɔʁize]","👍",["促进","有利于"],["to promote","to favour"],
      ["Le sport favorise la santé.","运动有益于健康。","Sport promotes good health."],
      ["Cette loi favorise les petites entreprises.","这项法律有利于小企业。","This law favours small businesses."],
      [{fr:"favoriser l'accès",zh:"促进获取"}],""),
    w("b2_012",L2,"méfiance","n.f.","阴性名词","f","[mefjɑ̃s]","🤨",["不信任","戒备"],["distrust","wariness"],
      ["Il regarde les publicités avec méfiance.","他对广告心存戒备。","He looks at ads with wariness."],
      ["Sa réponse a éveillé ma méfiance.","他的回答引起了我的戒心。","His answer aroused my distrust."],
      [{fr:"éveiller la méfiance",zh:"引起戒心"}],""),
    w("b2_013",L2,"engagement","n.m.","阳性名词","m","[ɑ̃ɡaʒmɑ̃]","✊",["承诺","投入"],["commitment"],
      ["Son engagement pour l'écologie est fort.","他对生态的投入很深。","His commitment to ecology is strong."],
      ["Elle tient toujours ses engagements.","她总是信守承诺。","She always keeps her commitments."],
      [{fr:"prendre un engagement",zh:"作出承诺"}],""),
    w("b2_014",L2,"remettre en cause","loc.","短语","","[ʁəmɛtʁ ɑ̃ koz]","❓",["质疑","重新审视"],["to call into question"],
      ["Il faut remettre en cause nos habitudes.","我们必须质疑自己的习惯。","We must call our habits into question."],
      ["Ces résultats remettent en cause la théorie.","这些结果对该理论提出了质疑。","These results call the theory into question."],
      [{fr:"remettre en cause un choix",zh:"质疑一个选择"}],""),
    w("b2_015",L2,"durable","adj.","形容词",null,"[dyʁabl]","♻️",["可持续的","持久的"],["sustainable","lasting"],
      ["Nous cherchons un développement durable.","我们追求可持续发展。","We're seeking sustainable development."],
      ["Ils ont bâti une paix durable.","他们建立了持久的和平。","They built a lasting peace."],
      [{fr:"développement durable",zh:"可持续发展"}],""),
    w("b2_016",L2,"solidarité","n.f.","阴性名词","f","[sɔlidaʁite]","🤲",["团结","互助"],["solidarity"],
      ["La solidarité entre voisins compte.","邻里之间的互助很重要。","Solidarity between neighbours matters."],
      ["La crise a renforcé la solidarité.","危机加强了团结。","The crisis strengthened solidarity."],
      [{fr:"élan de solidarité",zh:"互助的热潮"}],""),
    w("b2_017",L2,"préjugé","n.m.","阳性名词","m","[pʁeʒyʒe]","🏷️",["偏见"],["prejudice"],
      ["Il faut lutter contre les préjugés.","必须消除偏见。","We must fight against prejudice."],
      ["Elle juge les gens sans préjugés.","她评价别人不带偏见。","She judges people without prejudice."],
      [{fr:"avoir des préjugés",zh:"抱有偏见"}],""),
    w("b2_018",L2,"croissance","n.f.","阴性名词","f","[kʁwasɑ̃s]","📊",["增长"],["growth"],
      ["La croissance économique ralentit.","经济增长在放缓。","Economic growth is slowing down."],
      ["L'entreprise connaît une forte croissance.","这家公司增长强劲。","The company is experiencing strong growth."],
      [{fr:"la croissance économique",zh:"经济增长"}],""),
    w("b2_019",L2,"répandre","v.","动词",null,"[ʁepɑ̃dʁ]","📡",["传播","散布"],["to spread"],
      ["Les rumeurs se répandent vite.","谣言传播得很快。","Rumours spread quickly."],
      ["Le vent a répandu la fumée partout.","风把烟雾吹得到处都是。","The wind spread the smoke everywhere."],
      [{fr:"se répandre",zh:"扩散"}],""),
    w("b2_020",L2,"enjeu","n.m.","阳性名词","m","[ɑ̃ʒø]","🎯",["利害","关键问题"],["stake","key issue"],
      ["Le climat est un enjeu majeur.","气候是一个重大议题。","Climate is a major issue."],
      ["L'emploi est un enjeu de cette élection.","就业是这次选举的一个关键问题。","Jobs are a key issue in this election."],
      [{fr:"un enjeu de taille",zh:"重大议题"}],"复数为 « enjeux »。"),
    w("b2_021",L2,"efficace","adj.","形容词",null,"[efikas]","⚙️",["有效的","高效的"],["effective","efficient"],
      ["Cette méthode est très efficace.","这个方法非常有效。","This method is very effective."],
      ["Il nous faut une solution efficace.","我们需要一个有效的解决方案。","We need an effective solution."],
      [{fr:"une solution efficace",zh:"有效的解决方案"}],""),
    w("b2_022",L2,"sensibiliser","v.","动词",null,"[sɑ̃sibilize]","📣",["使…意识到","提高意识"],["to raise awareness"],
      ["Il faut sensibiliser les jeunes au tri.","要提高年轻人对垃圾分类的意识。","We must raise young people's awareness of recycling."],
      ["La campagne vise à sensibiliser le public.","这场活动旨在提高公众意识。","The campaign aims to raise public awareness."],
      [{fr:"sensibiliser le public",zh:"提高公众意识"}],""),

    /* ---------------- DALF C1 : soutenu, presse, abstraction ---------------- */
    w("c1_001",L3,"néanmoins","adv.","副词",null,"[neɑ̃mwɛ̃]","🔄",["然而","尽管如此"],["nevertheless"],
      ["Le projet est risqué ; néanmoins, il mérite d'être tenté.","这个项目有风险；然而，它值得一试。","The project is risky; nevertheless, it's worth attempting."],
      ["Il était fatigué ; néanmoins, il a terminé.","他很累；尽管如此，他还是完成了。","He was tired; nevertheless, he finished."],
      [{fr:"néanmoins, il faut",zh:"然而，必须"}],"书面连接词，比 « mais » 更正式。"),
    w("c1_002",L3,"pertinence","n.f.","阴性名词","f","[pɛʁtinɑ̃s]","🎯",["中肯","切题"],["relevance"],
      ["On peut douter de la pertinence de cet argument.","人们可以怀疑这个论点是否切题。","One may doubt the relevance of this argument."],
      ["La pertinence de son analyse a convaincu le jury.","她分析的中肯性说服了评委。","The relevance of her analysis convinced the panel."],
      [{fr:"la pertinence d'une analyse",zh:"分析的中肯性"}],""),
    w("c1_003",L3,"nuance","n.f.","阴性名词","f","[nɥɑ̃s]","🎨",["细微差别","微妙之处"],["nuance","subtle difference"],
      ["Il faut apporter des nuances à ce jugement.","应该对这一判断加以细化。","This judgement needs some nuance."],
      ["Il y a une nuance entre ces deux mots.","这两个词之间有细微差别。","There's a subtle difference between these two words."],
      [{fr:"apporter une nuance",zh:"加以细化"}],""),
    w("c1_004",L3,"souligner","v.","动词",null,"[suliɲe]","✏️",["强调","指出"],["to emphasise","to underline"],
      ["L'auteur souligne l'importance du débat.","作者强调了这场辩论的重要性。","The author emphasises the importance of the debate."],
      ["Je voudrais souligner un dernier point.","我想强调最后一点。","I'd like to underline one last point."],
      [{fr:"souligner un point",zh:"强调一点"}],""),
    w("c1_005",L3,"paradoxe","n.m.","阳性名词","m","[paʁadɔks]","🔀",["悖论","矛盾"],["paradox"],
      ["C'est un paradoxe apparent.","这是一个表面上的悖论。","It's an apparent paradox."],
      ["Le paradoxe, c'est qu'il gagne en perdant.","悖论在于，他输了却赢了。","The paradox is that he wins by losing."],
      [{fr:"un paradoxe frappant",zh:"惊人的悖论"}],""),
    w("c1_006",L3,"préconiser","v.","动词",null,"[pʁekɔnize]","📢",["建议","主张"],["to recommend","to advocate"],
      ["L'expert préconise la prudence.","专家主张谨慎行事。","The expert recommends caution."],
      ["Le rapport préconise plusieurs réformes.","报告建议进行多项改革。","The report advocates several reforms."],
      [{fr:"préconiser une mesure",zh:"主张采取措施"}],""),
    w("c1_007",L3,"ambiguïté","n.f.","阴性名词","f","[ɑ̃biɡɥite]","🌫️",["含糊","歧义"],["ambiguity"],
      ["Son discours entretient l'ambiguïté.","他的讲话保持着一种含糊。","His speech maintains ambiguity."],
      ["Il faut lever toute ambiguïté.","必须消除一切歧义。","All ambiguity must be removed."],
      [{fr:"lever l'ambiguïté",zh:"消除歧义"}],""),
    w("c1_008",L3,"remarquable","adj.","形容词",null,"[ʁəmaʁkabl]","🌟",["卓越的","显著的"],["remarkable"],
      ["Elle a fait un travail remarquable.","她做出了出色的工作。","She did remarkable work."],
      ["C'est un exploit vraiment remarquable.","这是一个非常了不起的成就。","It's a truly remarkable feat."],
      [{fr:"un effort remarquable",zh:"显著的努力"}],""),
    w("c1_009",L3,"inéluctable","adj.","形容词",null,"[inelyktabl]","⏳",["不可避免的"],["inevitable","inescapable"],
      ["Le changement paraît inéluctable.","这一变化似乎不可避免。","The change seems inevitable."],
      ["La défaite était devenue inéluctable.","失败已成定局。","Defeat had become inevitable."],
      [{fr:"une issue inéluctable",zh:"不可避免的结局"}],""),
    w("c1_010",L3,"discernement","n.m.","阳性名词","m","[disɛʁnəmɑ̃]","🧭",["辨别力","判断力"],["discernment","good judgement"],
      ["Il agit toujours avec discernement.","他做事总是有分寸。","He always acts with good judgement."],
      ["Ce choix demande du discernement.","这个选择需要判断力。","This choice requires discernment."],
      [{fr:"faire preuve de discernement",zh:"表现出判断力"}],""),
    w("c1_011",L3,"contrecarrer","v.","动词",null,"[kɔ̃tʁəkaʁe]","🛑",["阻挠","挫败"],["to thwart"],
      ["Ils cherchent à contrecarrer ce projet.","他们试图阻挠这个计划。","They're trying to thwart this project."],
      ["Rien ne pouvait contrecarrer sa volonté.","什么都无法阻挡他的意志。","Nothing could thwart his will."],
      [{fr:"contrecarrer un plan",zh:"挫败一个计划"}],""),
    w("c1_012",L3,"consensus","n.m.","阳性名词","m","[kɔ̃sɛ̃sys]","🤝",["共识"],["consensus"],
      ["Un consensus s'est dégagé de la réunion.","会议达成了共识。","A consensus emerged from the meeting."],
      ["Il est difficile de trouver un consensus.","达成共识很难。","It's hard to reach a consensus."],
      [{fr:"trouver un consensus",zh:"达成共识"}],""),
    w("c1_013",L3,"exacerber","v.","动词",null,"[ɛɡzasɛʁbe]","🔥",["加剧","激化"],["to exacerbate"],
      ["La crise exacerbe les tensions.","危机激化了紧张局势。","The crisis exacerbates tensions."],
      ["Ses propos ont exacerbé la colère de la foule.","他的言论加剧了人群的愤怒。","His words exacerbated the crowd's anger."],
      [{fr:"exacerber un conflit",zh:"激化冲突"}],""),
    w("c1_014",L3,"perspicace","adj.","形容词",null,"[pɛʁspikas]","🔍",["敏锐的","有洞察力的"],["perceptive","shrewd"],
      ["C'est une observatrice perspicace.","她是位敏锐的观察者。","She's a perceptive observer."],
      ["Une remarque perspicace a changé le débat.","一句敏锐的评论改变了辩论。","A shrewd remark changed the debate."],
      [{fr:"un esprit perspicace",zh:"敏锐的头脑"}],""),
    w("c1_015",L3,"préalable","adj.","形容词",null,"[pʁealabl]","1️⃣",["事先的","前提的"],["prior","preliminary"],
      ["Une réflexion préalable est nécessaire.","事先的思考是必要的。","Prior thought is necessary."],
      ["Aucune condition préalable n'est exigée.","无需任何前提条件。","No prior condition is required."],
      [{fr:"un accord préalable",zh:"事先的同意"}],""),
    w("c1_016",L3,"entériner","v.","动词",null,"[ɑ̃teʁine]","🖋️",["批准","确认"],["to ratify","to endorse"],
      ["Le conseil a entériné la décision.","理事会批准了这一决定。","The council ratified the decision."],
      ["Le vote a entériné l'accord.","投票确认了这项协议。","The vote endorsed the agreement."],
      [{fr:"entériner un accord",zh:"批准协议"}],""),
    w("c1_017",L3,"prépondérant","adj.","形容词",null,"[pʁepɔ̃deʁɑ̃]","⭐",["占主导的","首要的"],["predominant"],
      ["Ce facteur joue un rôle prépondérant.","这个因素起着主导作用。","This factor plays a predominant role."],
      ["Son influence est devenue prépondérante.","他的影响力变得举足轻重。","His influence has become predominant."],
      [{fr:"un rôle prépondérant",zh:"主导作用"}],""),
    w("c1_018",L3,"susciter","v.","动词",null,"[sysite]","💥",["引起","激起"],["to arouse","to provoke"],
      ["Ce film a suscité de vives réactions.","这部电影引起了强烈反响。","This film aroused strong reactions."],
      ["La nouvelle a suscité beaucoup d'espoir.","这个消息激起了很多希望。","The news aroused a lot of hope."],
      [{fr:"susciter l'intérêt",zh:"激起兴趣"}],""),
    w("c1_019",L3,"corollaire","n.m.","阳性名词","m","[kɔʁɔlɛʁ]","🔗",["必然结果","推论"],["corollary"],
      ["La liberté a pour corollaire la responsabilité.","自由的必然结果是责任。","Freedom has responsibility as its corollary."],
      ["La hausse des prix est le corollaire de la pénurie.","物价上涨是短缺的必然结果。","Rising prices are the corollary of shortage."],
      [{fr:"le corollaire de",zh:"…的必然结果"}],""),
    w("c1_020",L3,"délibéré","adj.","形容词",null,"[delibeʁe]","🎯",["蓄意的","深思熟虑的"],["deliberate"],
      ["C'est un choix délibéré.","这是一个深思熟虑的选择。","It's a deliberate choice."],
      ["Il a agi de manière délibérée.","他是有意为之。","He acted in a deliberate manner."],
      [{fr:"de manière délibérée",zh:"有意地"}],""),

    /* ---------------- DALF C2 : littéraire, très soutenu, figé ---------------- */
    w("c2_001",L4,"idoine","adj.","形容词",null,"[idwan]","🧩",["恰当的","合适的"],["apt","fitting"],
      ["Il a trouvé le mot idoine.","他找到了恰如其分的词。","He found just the right word."],
      ["On cherche la personne idoine pour ce poste.","我们在为这个职位寻找合适的人选。","We're looking for the fitting person for this role."],
      [{fr:"la solution idoine",zh:"恰当的方案"}],"极书面用语。"),
    w("c2_002",L4,"protéiforme","adj.","形容词",null,"[pʁɔteifɔʁm]","🌀",["多变的","变化多端的"],["protean","ever-changing"],
      ["Une menace protéiforme et insaisissable.","一种变化多端、难以捉摸的威胁。","A protean, elusive threat."],
      ["Son talent protéiforme étonne la critique.","他多变的才华令评论界惊叹。","His protean talent astonishes the critics."],
      [{fr:"un phénomène protéiforme",zh:"多变的现象"}],""),
    w("c2_003",L4,"obédience","n.f.","阴性名词","f","[ɔbedjɑ̃s]","🏛️",["派别","归属"],["allegiance","persuasion"],
      ["Un penseur d'obédience libérale.","一位属于自由派的思想家。","A thinker of liberal persuasion."],
      ["Ces pays sont d'obédience communiste.","这些国家属于共产主义阵营。","These countries are of communist allegiance."],
      [{fr:"d'obédience",zh:"属于…派别"}],""),
    w("c2_004",L4,"sciemment","adv.","副词",null,"[sjamɑ̃]","🎭",["故意地","明知地"],["knowingly"],
      ["Il a sciemment ignoré l'avertissement.","他明知故犯，无视了警告。","He knowingly ignored the warning."],
      ["Elle a sciemment caché la vérité.","她故意隐瞒了真相。","She knowingly hid the truth."],
      [{fr:"agir sciemment",zh:"故意行事"}],""),
    w("c2_005",L4,"palinodie","n.f.","阴性名词","f","[palinɔdi]","🔃",["自食其言","变卦"],["recantation","about-face"],
      ["Ses palinodies lassent l'auditoire.","他反复变卦让听众厌倦。","His about-faces weary the audience."],
      ["La presse a moqué sa palinodie.","媒体嘲笑了他的出尔反尔。","The press mocked his recantation."],
      [{fr:"une palinodie politique",zh:"政治上的出尔反尔"}],""),
    w("c2_006",L4,"prégnance","n.f.","阴性名词","f","[pʁeɡnɑ̃s]","🧲",["强烈影响","深刻印记"],["pervasive influence","salience"],
      ["La prégnance du mythe dans l'œuvre.","神话在作品中的深刻印记。","The pervasive presence of the myth in the work."],
      ["La prégnance de ce souvenir le hante.","这段回忆的强烈印记萦绕着他。","The salience of that memory haunts him."],
      [{fr:"la prégnance d'une image",zh:"某个意象的深刻印记"}],""),
    w("c2_007",L4,"éculé","adj.","形容词",null,"[ekyle]","👞",["陈旧的","用滥的"],["hackneyed","worn-out"],
      ["Un argument éculé et sans force.","一个用滥了、毫无说服力的论点。","A hackneyed, feeble argument."],
      ["Il recycle des clichés éculés.","他重复着陈腐的套话。","He recycles worn-out clichés."],
      [{fr:"un procédé éculé",zh:"陈旧的手法"}],""),
    w("c2_008",L4,"prolixe","adj.","形容词",null,"[pʁɔliks]","🗯️",["冗长的","啰嗦的"],["verbose","long-winded"],
      ["Un auteur brillant mais prolixe.","一位才华横溢却啰嗦的作者。","A brilliant but verbose author."],
      ["Sa préface, trop prolixe, lasse le lecteur.","他那过于冗长的前言让读者厌倦。","His overly verbose preface wearies the reader."],
      [{fr:"un style prolixe",zh:"冗长的文风"}],""),
    w("c2_009",L4,"achoppement","n.m.","阳性名词","m","[aʃɔpmɑ̃]","🪨",["障碍","症结"],["stumbling block"],
      ["La pierre d'achoppement des négociations.","谈判的症结所在。","The stumbling block of the negotiations."],
      ["Le financement reste le principal achoppement.","资金仍是主要症结。","Funding remains the main stumbling block."],
      [{fr:"pierre d'achoppement",zh:"绊脚石"}],""),
    w("c2_010",L4,"consubstantiel","adj.","形容词",null,"[kɔ̃sypstɑ̃sjɛl]","🔗",["本质相连的","同体的"],["consubstantial","inherently bound"],
      ["Une liberté consubstantielle à la démocratie.","一种与民主本质相连的自由。","A freedom consubstantial with democracy."],
      ["Le risque est consubstantiel à toute entreprise.","风险与任何事业本质相连。","Risk is inherent to any venture."],
      [{fr:"consubstantiel à",zh:"与…本质相连"}],""),
    w("c2_011",L4,"délétère","adj.","形容词",null,"[deletɛʁ]","☣️",["有害的","毒害的"],["deleterious","noxious"],
      ["Un climat délétère régnait dans l'équipe.","团队里弥漫着一种有害的氛围。","A noxious atmosphere reigned in the team."],
      ["Ces rumeurs ont un effet délétère.","这些谣言有毒害作用。","These rumours have a deleterious effect."],
      [{fr:"une influence délétère",zh:"毒害性的影响"}],""),
    w("c2_012",L4,"exégèse","n.f.","阴性名词","f","[ɛɡzeʒɛz]","📜",["诠释","解经"],["exegesis"],
      ["Son exégèse du texte est subtile.","他对文本的诠释很精妙。","His exegesis of the text is subtle."],
      ["Cette exégèse éclaire le poème.","这一诠释阐明了这首诗。","This exegesis illuminates the poem."],
      [{fr:"se livrer à l'exégèse",zh:"进行诠释"}],""),
    w("c2_013",L4,"velléité","n.f.","阴性名词","f","[veleite]","🌫️",["三分钟热度","微弱意愿"],["vague intention","half-hearted urge"],
      ["De simples velléités de réforme.","不过是些改革的空想罢了。","Mere half-hearted urges to reform."],
      ["Il n'a que des velléités d'écrire.","他不过是有点想写作的念头罢了。","He has only vague intentions of writing."],
      [{fr:"des velléités de",zh:"…的空想"}],""),
    w("c2_014",L4,"emphase","n.f.","阴性名词","f","[ɑ̃faz]","🎺",["夸张","浮夸"],["bombast","overemphasis"],
      ["Il parle avec emphase.","他说话很浮夸。","He speaks with bombast."],
      ["Le discours, plein d'emphase, sonnait faux.","那充满浮夸的演讲显得虚假。","The bombastic speech rang false."],
      [{fr:"parler avec emphase",zh:"夸张地说"}],""),
    w("c2_015",L4,"laconique","adj.","形容词",null,"[lakɔnik]","🤐",["简洁的","言简意赅的"],["laconic","terse"],
      ["Une réponse laconique et tranchante.","一个简洁而干脆的回答。","A laconic, cutting reply."],
      ["Son télégramme était laconique.","他的电报很简短。","His telegram was terse."],
      [{fr:"un ton laconique",zh:"简洁的语气"}],""),
    w("c2_016",L4,"sagacité","n.f.","阴性名词","f","[saɡasite]","🦉",["睿智","洞察力"],["sagacity","shrewdness"],
      ["Il a analysé la situation avec sagacité.","他睿智地分析了局势。","He analysed the situation with sagacity."],
      ["Sa sagacité lui a évité bien des pièges.","他的睿智让他避开了许多陷阱。","His shrewdness spared him many pitfalls."],
      [{fr:"faire preuve de sagacité",zh:"展现出睿智"}],""),
    w("c2_017",L4,"tergiverser","v.","动词",null,"[tɛʁʒivɛʁse]","🌀",["支吾","拖延推诿"],["to prevaricate","to dither"],
      ["Cesse de tergiverser et décide-toi.","别再推诿，快做决定。","Stop dithering and make up your mind."],
      ["Le gouvernement tergiverse depuis des mois.","政府已经推诿了好几个月。","The government has been prevaricating for months."],
      [{fr:"tergiverser sans fin",zh:"没完没了地推诿"}],""),
    w("c2_018",L4,"pusillanime","adj.","形容词",null,"[pyzilanim]","🐁",["胆小的","懦弱的"],["pusillanimous","faint-hearted"],
      ["Une attitude pusillanime devant le danger.","面对危险的一种懦弱态度。","A faint-hearted attitude in the face of danger."],
      ["Un chef pusillanime perd la confiance des siens.","懦弱的领导会失去下属的信任。","A pusillanimous leader loses his people's trust."],
      [{fr:"un chef pusillanime",zh:"懦弱的领导"}],""),
    w("c2_019",L4,"apophtegme","n.m.","阳性名词","m","[apɔftɛɡm]","💬",["格言","箴言"],["apothegm","maxim"],
      ["Il ponctue ses discours d'apophtegmes.","他的讲话中不时穿插格言。","He punctuates his speeches with apothegms."],
      ["Cet apophtegme résume toute sa pensée.","这句箴言概括了他的全部思想。","This maxim sums up his entire thought."],
      [{fr:"citer un apophtegme",zh:"引用格言"}],""),
    w("c2_020",L4,"éluder","v.","动词",null,"[elyde]","🙈",["回避","躲闪"],["to evade","to sidestep"],
      ["Le ministre a éludé la question.","部长回避了这个问题。","The minister evaded the question."],
      ["On ne peut pas éluder ce problème.","这个问题无法回避。","We can't sidestep this problem."],
      [{fr:"éluder une question",zh:"回避问题"}],"")
  ];
  window.VOCAB_DATA={
    levels:[L1,L2,L3,L4],
    levelLabel:{DELF_B1:"DELF B1",DELF_B2:"DELF B2",DALF_C1:"DALF C1",DALF_C2:"DALF C2"},
    levelZh:{DELF_B1:"B1 日常",DELF_B2:"B2 社会",DALF_C1:"C1 高级",DALF_C2:"C2 精通"},
    words:WORDS
  };
})();
