/* ============================================================================
   VOCAB_DATA — Banque de vocabulaire français DELF/DALF (module 百词斩)
   Format conforme au brief §6.3. Contenu 100 % hors-ligne.
   « image » = emoji (association visuelle façon 百词斩, sans pipeline d'images).
   Chaque mot : traduction 中文 + anglais (apprenants anglophones), IPA, emoji,
   DEUX exemples (fr / 中 / en), collocations et notes.
   ========================================================================== */
(function(){
  "use strict";
  // ex1 / ex2 = [phrase_fr, traduction_zh, traduction_en]
  function w(id,level,word,pos,pos_zh,gender,ipa,emoji,zh,en,ex1,ex2,coll,notes){
    return {id:id,level:level,word:word,pos:pos,pos_zh:pos_zh,gender:gender,ipa:ipa,emoji:emoji,
      zh:zh,en:en||[],
      ex_fr:ex1[0],ex_zh:ex1[1],ex_en:ex1[2],
      ex2_fr:ex2?ex2[0]:"",ex2_zh:ex2?ex2[1]:"",ex2_en:ex2?ex2[2]:"",
      coll:coll||[],notes:notes||""};
  }
  var L1="DELF_B1", L2="DELF_B2", L3="DALF_C1", L4="DALF_C2";
  var WORDS=[
    /* ---------------- DELF B1 : quotidien, voyages, travail, sentiments ---------------- */
    w("b1_001",L1,"améliorer","v.","动词",null,"[ameljɔʁe]","📈",["改善","提高"],["to improve"],
      ["Je voudrais améliorer mon niveau de français.","我想提高我的法语水平。","I'd like to improve my level of French."],
      ["Ces exercices aident à améliorer la prononciation.","这些练习有助于改善发音。","These exercises help improve pronunciation."],
      [{fr:"améliorer la qualité",zh:"提高质量"}],"注意区分 « améliorer »（改善某物）和 « s'améliorer »（自身变好）。"),
    w("b1_002",L1,"voyage","n.m.","阳性名词","m","[vwajaʒ]","🧳",["旅行","旅程"],["trip","journey"],
      ["Nous préparons un voyage en Italie.","我们在准备一次去意大利的旅行。","We're planning a trip to Italy."],
      ["Le voyage en train a duré six heures.","火车旅程持续了六个小时。","The train journey lasted six hours."],
      [{fr:"partir en voyage",zh:"去旅行"}],""),
    w("b1_003",L1,"quotidien","adj.","形容词",null,"[kɔtidjɛ̃]","📅",["日常的","每天的"],["daily","everyday"],
      ["La vie quotidienne à Paris est chère.","巴黎的日常生活很贵。","Daily life in Paris is expensive."],
      ["Il fait du sport de façon quotidienne.","他每天都运动。","He exercises on a daily basis."],
      [{fr:"la vie quotidienne",zh:"日常生活"}],""),
    w("b1_004",L1,"réussir","v.","动词",null,"[ʁeysiʁ]","🏆",["成功","考取"],["to succeed","to pass"],
      ["Elle a réussi son examen.","她考试通过了。","She passed her exam."],
      ["Avec du travail, tu vas réussir.","只要努力，你会成功的。","With hard work, you'll succeed."],
      [{fr:"réussir un examen",zh:"通过考试"}],""),
    w("b1_005",L1,"inquiet","adj.","形容词",null,"[ɛ̃kjɛ]","😟",["担心的","不安的"],["worried","anxious"],
      ["Je suis inquiet pour mon avenir.","我为我的未来感到担心。","I'm worried about my future."],
      ["Sa mère est inquiète quand il rentre tard.","他晚归时母亲会担心。","His mother gets worried when he comes home late."],
      [{fr:"être inquiet",zh:"感到担心"}],"阴性形式为 « inquiète »。"),
    w("b1_006",L1,"souvenir","n.m.","阳性名词","m","[suvniʁ]","📸",["回忆","纪念品"],["memory","souvenir"],
      ["J'ai de bons souvenirs de ce voyage.","我对这次旅行有美好的回忆。","I have good memories of that trip."],
      ["Elle a rapporté un souvenir de Rome.","她从罗马带回了一件纪念品。","She brought back a souvenir from Rome."],
      [{fr:"garder un souvenir",zh:"留下回忆"}],""),
    w("b1_007",L1,"entreprise","n.f.","阴性名词","f","[ɑ̃tʁəpʁiz]","🏢",["公司","企业"],["company","business"],
      ["Il travaille dans une grande entreprise.","他在一家大公司工作。","He works in a big company."],
      ["Elle a créé son entreprise à trente ans.","她三十岁时创办了自己的公司。","She started her own business at thirty."],
      [{fr:"créer une entreprise",zh:"创办公司"}],""),
    w("b1_008",L1,"conseil","n.m.","阳性名词","m","[kɔ̃sɛj]","💡",["建议","忠告"],["advice","piece of advice"],
      ["Merci pour tes conseils.","谢谢你的建议。","Thanks for your advice."],
      ["Le médecin m'a donné un bon conseil.","医生给了我一个很好的建议。","The doctor gave me a good piece of advice."],
      [{fr:"donner un conseil",zh:"给建议"}],""),
    w("b1_009",L1,"emprunter","v.","动词",null,"[ɑ̃pʁœ̃te]","🔁",["借入","借用"],["to borrow"],
      ["Je peux emprunter ton stylo ?","我能借用你的笔吗？","Can I borrow your pen?"],
      ["Il a emprunté un livre à la bibliothèque.","他从图书馆借了一本书。","He borrowed a book from the library."],
      [{fr:"emprunter de l'argent",zh:"借钱"}],"« emprunter »（借入）≠ « prêter »（借出）。"),
    w("b1_010",L1,"gentil","adj.","形容词",null,"[ʒɑ̃ti]","😊",["善良的","友好的"],["kind","nice"],
      ["Ta voisine est très gentille.","你的邻居非常友好。","Your neighbour is very kind."],
      ["C'est gentil de m'aider.","你帮我真好。","It's kind of you to help me."],
      [{fr:"être gentil avec",zh:"对…友好"}],""),
    w("b1_011",L1,"santé","n.f.","阴性名词","f","[sɑ̃te]","🩺",["健康"],["health"],
      ["La santé est plus importante que l'argent.","健康比金钱更重要。","Health is more important than money."],
      ["Le sport est bon pour la santé.","运动有益健康。","Exercise is good for your health."],
      [{fr:"être en bonne santé",zh:"身体健康"}],""),
    w("b1_012",L1,"décider","v.","动词",null,"[deside]","✅",["决定"],["to decide"],
      ["Nous avons décidé de partir demain.","我们决定明天出发。","We've decided to leave tomorrow."],
      ["C'est à toi de décider.","由你来决定。","It's up to you to decide."],
      [{fr:"décider de faire",zh:"决定做某事"}],""),
    w("b1_013",L1,"météo","n.f.","阴性名词","f","[meteo]","🌦️",["天气预报","天气"],["weather","weather forecast"],
      ["La météo annonce de la pluie.","天气预报说要下雨。","The forecast says it will rain."],
      ["On regarde la météo avant de partir.","出发前我们看看天气预报。","We check the weather before leaving."],
      [{fr:"regarder la météo",zh:"看天气预报"}],""),
    w("b1_014",L1,"cuisine","n.f.","阴性名词","f","[kɥizin]","🍳",["厨房","烹饪"],["kitchen","cooking","cuisine"],
      ["J'adore la cuisine française.","我很喜欢法国菜。","I love French cuisine."],
      ["Elle prépare le dîner dans la cuisine.","她在厨房里准备晚饭。","She's making dinner in the kitchen."],
      [{fr:"faire la cuisine",zh:"做饭"}],""),
    w("b1_015",L1,"fatigué","adj.","形容词",null,"[fatiɡe]","😴",["疲惫的","累的"],["tired"],
      ["Je suis très fatigué ce soir.","我今晚很累。","I'm very tired tonight."],
      ["Après la course, il était fatigué.","跑步之后他很累。","After the run, he was tired."],
      [{fr:"se sentir fatigué",zh:"感到疲惫"}],""),
    w("b1_016",L1,"argent","n.m.","阳性名词","m","[aʁʒɑ̃]","💰",["钱","银"],["money","silver"],
      ["Je n'ai pas assez d'argent.","我的钱不够。","I don't have enough money."],
      ["Il gagne bien son argent.","他挣钱不少。","He earns good money."],
      [{fr:"gagner de l'argent",zh:"赚钱"}],""),
    w("b1_017",L1,"rencontrer","v.","动词",null,"[ʁɑ̃kɔ̃tʁe]","🤝",["遇见","结识"],["to meet"],
      ["J'ai rencontré un ami en ville.","我在城里遇见了一个朋友。","I met a friend in town."],
      ["Ils se sont rencontrés à l'université.","他们在大学里相识。","They met at university."],
      [{fr:"rencontrer quelqu'un",zh:"遇见某人"}],""),
    w("b1_018",L1,"heureux","adj.","形容词",null,"[œʁø]","😄",["幸福的","高兴的"],["happy"],
      ["Ils sont heureux ensemble.","他们在一起很幸福。","They're happy together."],
      ["Je suis heureux de vous rencontrer.","很高兴认识您。","I'm happy to meet you."],
      [{fr:"rendre heureux",zh:"使…幸福"}],"阴性形式为 « heureuse »。"),
    w("b1_019",L1,"gare","n.f.","阴性名词","f","[ɡaʁ]","🚉",["火车站"],["(train) station"],
      ["Le train part de la gare à midi.","火车中午从车站出发。","The train leaves the station at noon."],
      ["On se retrouve devant la gare.","我们在火车站前碰面。","Let's meet in front of the station."],
      [{fr:"aller à la gare",zh:"去火车站"}],""),
    w("b1_020",L1,"projet","n.m.","阳性名词","m","[pʁɔʒɛ]","📋",["计划","项目"],["project","plan"],
      ["Elle a un projet intéressant.","她有一个有趣的计划。","She has an interesting project."],
      ["Nous avons des projets pour cet été.","我们对今年夏天有一些计划。","We have plans for this summer."],
      [{fr:"réaliser un projet",zh:"实现计划"}],""),
    w("b1_021",L1,"oublier","v.","动词",null,"[ublije]","🤦",["忘记"],["to forget"],
      ["N'oublie pas ton passeport !","别忘了你的护照！","Don't forget your passport!"],
      ["J'ai oublié son nom.","我忘了他的名字。","I've forgotten his name."],
      [{fr:"oublier de faire",zh:"忘了做某事"}],""),
    w("b1_022",L1,"cadeau","n.m.","阳性名词","m","[kado]","🎁",["礼物"],["gift","present"],
      ["C'est un cadeau pour toi.","这是给你的礼物。","It's a present for you."],
      ["Ils offrent des cadeaux à Noël.","他们在圣诞节送礼物。","They give gifts at Christmas."],
      [{fr:"offrir un cadeau",zh:"送礼物"}],"复数为 « cadeaux »。"),
    w("b1_023",L1,"content","adj.","形容词",null,"[kɔ̃tɑ̃]","🙂",["满意的","高兴的"],["glad","pleased"],
      ["Je suis content de te voir.","见到你我很高兴。","I'm glad to see you."],
      ["Elle est contente de son travail.","她对自己的工作很满意。","She's pleased with her work."],
      [{fr:"être content de",zh:"对…满意"}],""),
    w("b1_024",L1,"voisin","n.m.","阳性名词","m","[vwazɛ̃]","🏠",["邻居"],["neighbour"],
      ["Mon voisin est musicien.","我的邻居是音乐家。","My neighbour is a musician."],
      ["Nous invitons les voisins ce soir.","我们今晚邀请邻居。","We're inviting the neighbours tonight."],
      [{fr:"un bon voisin",zh:"好邻居"}],""),

    /* ---------------- DELF B2 : argumentation, société, environnement ---------------- */
    w("b2_001",L2,"environnement","n.m.","阳性名词","m","[ɑ̃viʁɔnmɑ̃]","🌍",["环境"],["environment"],
      ["Il faut protéger l'environnement.","必须保护环境。","We must protect the environment."],
      ["La pollution nuit à l'environnement.","污染损害环境。","Pollution harms the environment."],
      [{fr:"protéger l'environnement",zh:"保护环境"}],""),
    w("b2_002",L2,"pollution","n.f.","阴性名词","f","[pɔlysjɔ̃]","🏭",["污染"],["pollution"],
      ["La pollution de l'air augmente en ville.","城市里的空气污染在加剧。","Air pollution is increasing in the city."],
      ["La ville lutte contre la pollution.","这座城市在治理污染。","The city is fighting pollution."],
      [{fr:"réduire la pollution",zh:"减少污染"}],""),
    w("b2_003",L2,"chômage","n.m.","阳性名词","m","[ʃomaʒ]","📉",["失业"],["unemployment"],
      ["Le taux de chômage a baissé.","失业率下降了。","The unemployment rate has fallen."],
      ["Il est au chômage depuis six mois.","他失业已经六个月了。","He has been unemployed for six months."],
      [{fr:"lutter contre le chômage",zh:"应对失业"}],""),
    w("b2_004",L2,"citoyen","n.m.","阳性名词","m","[sitwajɛ̃]","🗳️",["公民"],["citizen"],
      ["Chaque citoyen a des droits.","每个公民都有权利。","Every citizen has rights."],
      ["Les citoyens votent dimanche.","公民们星期天投票。","Citizens vote on Sunday."],
      [{fr:"un citoyen responsable",zh:"负责任的公民"}],""),
    w("b2_005",L2,"débat","n.m.","阳性名词","m","[deba]","💬",["辩论","讨论"],["debate"],
      ["Le débat sur l'école continue.","关于学校的辩论仍在继续。","The debate about schools continues."],
      ["Le sujet a lancé un vif débat.","这个话题引发了激烈辩论。","The topic sparked a lively debate."],
      [{fr:"lancer un débat",zh:"发起讨论"}],""),
    w("b2_006",L2,"inégalité","n.f.","阴性名词","f","[inegalite]","⚖️",["不平等"],["inequality"],
      ["Les inégalités sociales se creusent.","社会不平等在加剧。","Social inequalities are widening."],
      ["L'école doit réduire les inégalités.","学校应当缩小不平等。","Schools should reduce inequalities."],
      [{fr:"réduire les inégalités",zh:"缩小不平等"}],""),
    w("b2_007",L2,"développer","v.","动词",null,"[devlɔpe]","🚀",["发展","开发"],["to develop"],
      ["L'entreprise veut développer ses activités.","公司想发展业务。","The company wants to develop its business."],
      ["Il faut développer votre argument.","你需要展开你的论点。","You need to develop your argument."],
      [{fr:"développer une idée",zh:"展开论述"}],""),
    w("b2_008",L2,"conséquence","n.f.","阴性名词","f","[kɔ̃sekɑ̃s]","➡️",["后果","结果"],["consequence"],
      ["Cette décision a de lourdes conséquences.","这个决定有严重后果。","This decision has serious consequences."],
      ["Il n'a pas mesuré les conséquences de son acte.","他没有意识到自己行为的后果。","He didn't realise the consequences of his action."],
      [{fr:"avoir des conséquences",zh:"产生后果"}],""),
    w("b2_009",L2,"nuisible","adj.","形容词",null,"[nɥizibl]","☠️",["有害的"],["harmful"],
      ["Le tabac est nuisible à la santé.","烟草对健康有害。","Tobacco is harmful to health."],
      ["Ces produits sont nuisibles pour l'environnement.","这些产品对环境有害。","These products are harmful to the environment."],
      [{fr:"nuisible à",zh:"对…有害"}],""),
    w("b2_010",L2,"gaspillage","n.m.","阳性名词","m","[ɡaspijaʒ]","🗑️",["浪费"],["waste"],
      ["Le gaspillage alimentaire est un problème.","食物浪费是个问题。","Food waste is a problem."],
      ["Réduire le gaspillage d'eau est essentiel.","减少水的浪费至关重要。","Reducing water waste is essential."],
      [{fr:"lutter contre le gaspillage",zh:"反对浪费"}],""),
    w("b2_011",L2,"favoriser","v.","动词",null,"[favɔʁize]","👍",["促进","有利于"],["to promote","to favour"],
      ["Le sport favorise la santé.","运动有益于健康。","Sport promotes good health."],
      ["Cette loi favorise les petites entreprises.","这项法律有利于小企业。","This law favours small businesses."],
      [{fr:"favoriser l'accès",zh:"促进获取"}],""),
    w("b2_012",L2,"méfiance","n.f.","阴性名词","f","[mefjɑ̃s]","🤨",["不信任","戒备"],["distrust","wariness"],
      ["Il regarde les publicités avec méfiance.","他对广告心存戒备。","He looks at ads with wariness."],
      ["Sa réponse a éveillé ma méfiance.","他的回答引起了我的戒心。","His answer aroused my distrust."],
      [{fr:"éveiller la méfiance",zh:"引起戒心"}],""),
    w("b2_013",L2,"engagement","n.m.","阳性名词","m","[ɑ̃ɡaʒmɑ̃]","✊",["承诺","投入"],["commitment"],
      ["Son engagement pour l'écologie est fort.","他对生态的投入很深。","His commitment to ecology is strong."],
      ["Elle tient toujours ses engagements.","她总是信守承诺。","She always keeps her commitments."],
      [{fr:"prendre un engagement",zh:"作出承诺"}],""),
    w("b2_014",L2,"remettre en cause","loc.","短语","","[ʁəmɛtʁ ɑ̃ koz]","❓",["质疑","重新审视"],["to call into question"],
      ["Il faut remettre en cause nos habitudes.","我们必须质疑自己的习惯。","We must call our habits into question."],
      ["Ces résultats remettent en cause la théorie.","这些结果对该理论提出了质疑。","These results call the theory into question."],
      [{fr:"remettre en cause un choix",zh:"质疑一个选择"}],""),
    w("b2_015",L2,"durable","adj.","形容词",null,"[dyʁabl]","♻️",["可持续的","持久的"],["sustainable","lasting"],
      ["Nous cherchons un développement durable.","我们追求可持续发展。","We're seeking sustainable development."],
      ["Ils ont bâti une paix durable.","他们建立了持久的和平。","They built a lasting peace."],
      [{fr:"développement durable",zh:"可持续发展"}],""),
    w("b2_016",L2,"solidarité","n.f.","阴性名词","f","[sɔlidaʁite]","🤲",["团结","互助"],["solidarity"],
      ["La solidarité entre voisins compte.","邻里之间的互助很重要。","Solidarity between neighbours matters."],
      ["La crise a renforcé la solidarité.","危机加强了团结。","The crisis strengthened solidarity."],
      [{fr:"élan de solidarité",zh:"互助的热潮"}],""),
    w("b2_017",L2,"préjugé","n.m.","阳性名词","m","[pʁeʒyʒe]","🏷️",["偏见"],["prejudice"],
      ["Il faut lutter contre les préjugés.","必须消除偏见。","We must fight against prejudice."],
      ["Elle juge les gens sans préjugés.","她评价别人不带偏见。","She judges people without prejudice."],
      [{fr:"avoir des préjugés",zh:"抱有偏见"}],""),
    w("b2_018",L2,"croissance","n.f.","阴性名词","f","[kʁwasɑ̃s]","📊",["增长"],["growth"],
      ["La croissance économique ralentit.","经济增长在放缓。","Economic growth is slowing down."],
      ["L'entreprise connaît une forte croissance.","这家公司增长强劲。","The company is experiencing strong growth."],
      [{fr:"la croissance économique",zh:"经济增长"}],""),
    w("b2_019",L2,"répandre","v.","动词",null,"[ʁepɑ̃dʁ]","📡",["传播","散布"],["to spread"],
      ["Les rumeurs se répandent vite.","谣言传播得很快。","Rumours spread quickly."],
      ["Le vent a répandu la fumée partout.","风把烟雾吹得到处都是。","The wind spread the smoke everywhere."],
      [{fr:"se répandre",zh:"扩散"}],""),
    w("b2_020",L2,"enjeu","n.m.","阳性名词","m","[ɑ̃ʒø]","🎯",["利害","关键问题"],["stake","key issue"],
      ["Le climat est un enjeu majeur.","气候是一个重大议题。","Climate is a major issue."],
      ["L'emploi est un enjeu de cette élection.","就业是这次选举的一个关键问题。","Jobs are a key issue in this election."],
      [{fr:"un enjeu de taille",zh:"重大议题"}],"复数为 « enjeux »。"),
    w("b2_021",L2,"efficace","adj.","形容词",null,"[efikas]","⚙️",["有效的","高效的"],["effective","efficient"],
      ["Cette méthode est très efficace.","这个方法非常有效。","This method is very effective."],
      ["Il nous faut une solution efficace.","我们需要一个有效的解决方案。","We need an effective solution."],
      [{fr:"une solution efficace",zh:"有效的解决方案"}],""),
    w("b2_022",L2,"sensibiliser","v.","动词",null,"[sɑ̃sibilize]","📣",["使…意识到","提高意识"],["to raise awareness"],
      ["Il faut sensibiliser les jeunes au tri.","要提高年轻人对垃圾分类的意识。","We must raise young people's awareness of recycling."],
      ["La campagne vise à sensibiliser le public.","这场活动旨在提高公众意识。","The campaign aims to raise public awareness."],
      [{fr:"sensibiliser le public",zh:"提高公众意识"}],""),

    /* ---------------- DALF C1 : soutenu, presse, abstraction ---------------- */
    w("c1_001",L3,"néanmoins","adv.","副词",null,"[neɑ̃mwɛ̃]","🔄",["然而","尽管如此"],["nevertheless"],
      ["Le projet est risqué ; néanmoins, il mérite d'être tenté.","这个项目有风险；然而，它值得一试。","The project is risky; nevertheless, it's worth attempting."],
      ["Il était fatigué ; néanmoins, il a terminé.","他很累；尽管如此，他还是完成了。","He was tired; nevertheless, he finished."],
      [{fr:"néanmoins, il faut",zh:"然而，必须"}],"书面连接词，比 « mais » 更正式。"),
    w("c1_002",L3,"pertinence","n.f.","阴性名词","f","[pɛʁtinɑ̃s]","🎯",["中肯","切题"],["relevance"],
      ["On peut douter de la pertinence de cet argument.","人们可以怀疑这个论点是否切题。","One may doubt the relevance of this argument."],
      ["La pertinence de son analyse a convaincu le jury.","她分析的中肯性说服了评委。","The relevance of her analysis convinced the panel."],
      [{fr:"la pertinence d'une analyse",zh:"分析的中肯性"}],""),
    w("c1_003",L3,"nuance","n.f.","阴性名词","f","[nɥɑ̃s]","🎨",["细微差别","微妙之处"],["nuance","subtle difference"],
      ["Il faut apporter des nuances à ce jugement.","应该对这一判断加以细化。","This judgement needs some nuance."],
      ["Il y a une nuance entre ces deux mots.","这两个词之间有细微差别。","There's a subtle difference between these two words."],
      [{fr:"apporter une nuance",zh:"加以细化"}],""),
    w("c1_004",L3,"souligner","v.","动词",null,"[suliɲe]","✏️",["强调","指出"],["to emphasise","to underline"],
      ["L'auteur souligne l'importance du débat.","作者强调了这场辩论的重要性。","The author emphasises the importance of the debate."],
      ["Je voudrais souligner un dernier point.","我想强调最后一点。","I'd like to underline one last point."],
      [{fr:"souligner un point",zh:"强调一点"}],""),
    w("c1_005",L3,"paradoxe","n.m.","阳性名词","m","[paʁadɔks]","🔀",["悖论","矛盾"],["paradox"],
      ["C'est un paradoxe apparent.","这是一个表面上的悖论。","It's an apparent paradox."],
      ["Le paradoxe, c'est qu'il gagne en perdant.","悖论在于，他输了却赢了。","The paradox is that he wins by losing."],
      [{fr:"un paradoxe frappant",zh:"惊人的悖论"}],""),
    w("c1_006",L3,"préconiser","v.","动词",null,"[pʁekɔnize]","📢",["建议","主张"],["to recommend","to advocate"],
      ["L'expert préconise la prudence.","专家主张谨慎行事。","The expert recommends caution."],
      ["Le rapport préconise plusieurs réformes.","报告建议进行多项改革。","The report advocates several reforms."],
      [{fr:"préconiser une mesure",zh:"主张采取措施"}],""),
    w("c1_007",L3,"ambiguïté","n.f.","阴性名词","f","[ɑ̃biɡɥite]","🌫️",["含糊","歧义"],["ambiguity"],
      ["Son discours entretient l'ambiguïté.","他的讲话保持着一种含糊。","His speech maintains ambiguity."],
      ["Il faut lever toute ambiguïté.","必须消除一切歧义。","All ambiguity must be removed."],
      [{fr:"lever l'ambiguïté",zh:"消除歧义"}],""),
    w("c1_008",L3,"remarquable","adj.","形容词",null,"[ʁəmaʁkabl]","🌟",["卓越的","显著的"],["remarkable"],
      ["Elle a fait un travail remarquable.","她做出了出色的工作。","She did remarkable work."],
      ["C'est un exploit vraiment remarquable.","这是一个非常了不起的成就。","It's a truly remarkable feat."],
      [{fr:"un effort remarquable",zh:"显著的努力"}],""),
    w("c1_009",L3,"inéluctable","adj.","形容词",null,"[inelyktabl]","⏳",["不可避免的"],["inevitable","inescapable"],
      ["Le changement paraît inéluctable.","这一变化似乎不可避免。","The change seems inevitable."],
      ["La défaite était devenue inéluctable.","失败已成定局。","Defeat had become inevitable."],
      [{fr:"une issue inéluctable",zh:"不可避免的结局"}],""),
    w("c1_010",L3,"discernement","n.m.","阳性名词","m","[disɛʁnəmɑ̃]","🧭",["辨别力","判断力"],["discernment","good judgement"],
      ["Il agit toujours avec discernement.","他做事总是有分寸。","He always acts with good judgement."],
      ["Ce choix demande du discernement.","这个选择需要判断力。","This choice requires discernment."],
      [{fr:"faire preuve de discernement",zh:"表现出判断力"}],""),
    w("c1_011",L3,"contrecarrer","v.","动词",null,"[kɔ̃tʁəkaʁe]","🛑",["阻挠","挫败"],["to thwart"],
      ["Ils cherchent à contrecarrer ce projet.","他们试图阻挠这个计划。","They're trying to thwart this project."],
      ["Rien ne pouvait contrecarrer sa volonté.","什么都无法阻挡他的意志。","Nothing could thwart his will."],
      [{fr:"contrecarrer un plan",zh:"挫败一个计划"}],""),
    w("c1_012",L3,"consensus","n.m.","阳性名词","m","[kɔ̃sɛ̃sys]","🤝",["共识"],["consensus"],
      ["Un consensus s'est dégagé de la réunion.","会议达成了共识。","A consensus emerged from the meeting."],
      ["Il est difficile de trouver un consensus.","达成共识很难。","It's hard to reach a consensus."],
      [{fr:"trouver un consensus",zh:"达成共识"}],""),
    w("c1_013",L3,"exacerber","v.","动词",null,"[ɛɡzasɛʁbe]","🔥",["加剧","激化"],["to exacerbate"],
      ["La crise exacerbe les tensions.","危机激化了紧张局势。","The crisis exacerbates tensions."],
      ["Ses propos ont exacerbé la colère de la foule.","他的言论加剧了人群的愤怒。","His words exacerbated the crowd's anger."],
      [{fr:"exacerber un conflit",zh:"激化冲突"}],""),
    w("c1_014",L3,"perspicace","adj.","形容词",null,"[pɛʁspikas]","🔍",["敏锐的","有洞察力的"],["perceptive","shrewd"],
      ["C'est une observatrice perspicace.","她是位敏锐的观察者。","She's a perceptive observer."],
      ["Une remarque perspicace a changé le débat.","一句敏锐的评论改变了辩论。","A shrewd remark changed the debate."],
      [{fr:"un esprit perspicace",zh:"敏锐的头脑"}],""),
    w("c1_015",L3,"préalable","adj.","形容词",null,"[pʁealabl]","1️⃣",["事先的","前提的"],["prior","preliminary"],
      ["Une réflexion préalable est nécessaire.","事先的思考是必要的。","Prior thought is necessary."],
      ["Aucune condition préalable n'est exigée.","无需任何前提条件。","No prior condition is required."],
      [{fr:"un accord préalable",zh:"事先的同意"}],""),
    w("c1_016",L3,"entériner","v.","动词",null,"[ɑ̃teʁine]","🖋️",["批准","确认"],["to ratify","to endorse"],
      ["Le conseil a entériné la décision.","理事会批准了这一决定。","The council ratified the decision."],
      ["Le vote a entériné l'accord.","投票确认了这项协议。","The vote endorsed the agreement."],
      [{fr:"entériner un accord",zh:"批准协议"}],""),
    w("c1_017",L3,"prépondérant","adj.","形容词",null,"[pʁepɔ̃deʁɑ̃]","⭐",["占主导的","首要的"],["predominant"],
      ["Ce facteur joue un rôle prépondérant.","这个因素起着主导作用。","This factor plays a predominant role."],
      ["Son influence est devenue prépondérante.","他的影响力变得举足轻重。","His influence has become predominant."],
      [{fr:"un rôle prépondérant",zh:"主导作用"}],""),
    w("c1_018",L3,"susciter","v.","动词",null,"[sysite]","💥",["引起","激起"],["to arouse","to provoke"],
      ["Ce film a suscité de vives réactions.","这部电影引起了强烈反响。","This film aroused strong reactions."],
      ["La nouvelle a suscité beaucoup d'espoir.","这个消息激起了很多希望。","The news aroused a lot of hope."],
      [{fr:"susciter l'intérêt",zh:"激起兴趣"}],""),
    w("c1_019",L3,"corollaire","n.m.","阳性名词","m","[kɔʁɔlɛʁ]","🔗",["必然结果","推论"],["corollary"],
      ["La liberté a pour corollaire la responsabilité.","自由的必然结果是责任。","Freedom has responsibility as its corollary."],
      ["La hausse des prix est le corollaire de la pénurie.","物价上涨是短缺的必然结果。","Rising prices are the corollary of shortage."],
      [{fr:"le corollaire de",zh:"…的必然结果"}],""),
    w("c1_020",L3,"délibéré","adj.","形容词",null,"[delibeʁe]","🎯",["蓄意的","深思熟虑的"],["deliberate"],
      ["C'est un choix délibéré.","这是一个深思熟虑的选择。","It's a deliberate choice."],
      ["Il a agi de manière délibérée.","他是有意为之。","He acted in a deliberate manner."],
      [{fr:"de manière délibérée",zh:"有意地"}],""),

    /* ---------------- DALF C2 : littéraire, très soutenu, figé ---------------- */
    w("c2_001",L4,"idoine","adj.","形容词",null,"[idwan]","🧩",["恰当的","合适的"],["apt","fitting"],
      ["Il a trouvé le mot idoine.","他找到了恰如其分的词。","He found just the right word."],
      ["On cherche la personne idoine pour ce poste.","我们在为这个职位寻找合适的人选。","We're looking for the fitting person for this role."],
      [{fr:"la solution idoine",zh:"恰当的方案"}],"极书面用语。"),
    w("c2_002",L4,"protéiforme","adj.","形容词",null,"[pʁɔteifɔʁm]","🌀",["多变的","变化多端的"],["protean","ever-changing"],
      ["Une menace protéiforme et insaisissable.","一种变化多端、难以捉摸的威胁。","A protean, elusive threat."],
      ["Son talent protéiforme étonne la critique.","他多变的才华令评论界惊叹。","His protean talent astonishes the critics."],
      [{fr:"un phénomène protéiforme",zh:"多变的现象"}],""),
    w("c2_003",L4,"obédience","n.f.","阴性名词","f","[ɔbedjɑ̃s]","🏛️",["派别","归属"],["allegiance","persuasion"],
      ["Un penseur d'obédience libérale.","一位属于自由派的思想家。","A thinker of liberal persuasion."],
      ["Ces pays sont d'obédience communiste.","这些国家属于共产主义阵营。","These countries are of communist allegiance."],
      [{fr:"d'obédience",zh:"属于…派别"}],""),
    w("c2_004",L4,"sciemment","adv.","副词",null,"[sjamɑ̃]","🎭",["故意地","明知地"],["knowingly"],
      ["Il a sciemment ignoré l'avertissement.","他明知故犯，无视了警告。","He knowingly ignored the warning."],
      ["Elle a sciemment caché la vérité.","她故意隐瞒了真相。","She knowingly hid the truth."],
      [{fr:"agir sciemment",zh:"故意行事"}],""),
    w("c2_005",L4,"palinodie","n.f.","阴性名词","f","[palinɔdi]","🔃",["自食其言","变卦"],["recantation","about-face"],
      ["Ses palinodies lassent l'auditoire.","他反复变卦让听众厌倦。","His about-faces weary the audience."],
      ["La presse a moqué sa palinodie.","媒体嘲笑了他的出尔反尔。","The press mocked his recantation."],
      [{fr:"une palinodie politique",zh:"政治上的出尔反尔"}],""),
    w("c2_006",L4,"prégnance","n.f.","阴性名词","f","[pʁeɡnɑ̃s]","🧲",["强烈影响","深刻印记"],["pervasive influence","salience"],
      ["La prégnance du mythe dans l'œuvre.","神话在作品中的深刻印记。","The pervasive presence of the myth in the work."],
      ["La prégnance de ce souvenir le hante.","这段回忆的强烈印记萦绕着他。","The salience of that memory haunts him."],
      [{fr:"la prégnance d'une image",zh:"某个意象的深刻印记"}],""),
    w("c2_007",L4,"éculé","adj.","形容词",null,"[ekyle]","👞",["陈旧的","用滥的"],["hackneyed","worn-out"],
      ["Un argument éculé et sans force.","一个用滥了、毫无说服力的论点。","A hackneyed, feeble argument."],
      ["Il recycle des clichés éculés.","他重复着陈腐的套话。","He recycles worn-out clichés."],
      [{fr:"un procédé éculé",zh:"陈旧的手法"}],""),
    w("c2_008",L4,"prolixe","adj.","形容词",null,"[pʁɔliks]","🗯️",["冗长的","啰嗦的"],["verbose","long-winded"],
      ["Un auteur brillant mais prolixe.","一位才华横溢却啰嗦的作者。","A brilliant but verbose author."],
      ["Sa préface, trop prolixe, lasse le lecteur.","他那过于冗长的前言让读者厌倦。","His overly verbose preface wearies the reader."],
      [{fr:"un style prolixe",zh:"冗长的文风"}],""),
    w("c2_009",L4,"achoppement","n.m.","阳性名词","m","[aʃɔpmɑ̃]","🪨",["障碍","症结"],["stumbling block"],
      ["La pierre d'achoppement des négociations.","谈判的症结所在。","The stumbling block of the negotiations."],
      ["Le financement reste le principal achoppement.","资金仍是主要症结。","Funding remains the main stumbling block."],
      [{fr:"pierre d'achoppement",zh:"绊脚石"}],""),
    w("c2_010",L4,"consubstantiel","adj.","形容词",null,"[kɔ̃sypstɑ̃sjɛl]","🔗",["本质相连的","同体的"],["consubstantial","inherently bound"],
      ["Une liberté consubstantielle à la démocratie.","一种与民主本质相连的自由。","A freedom consubstantial with democracy."],
      ["Le risque est consubstantiel à toute entreprise.","风险与任何事业本质相连。","Risk is inherent to any venture."],
      [{fr:"consubstantiel à",zh:"与…本质相连"}],""),
    w("c2_011",L4,"délétère","adj.","形容词",null,"[deletɛʁ]","☣️",["有害的","毒害的"],["deleterious","noxious"],
      ["Un climat délétère régnait dans l'équipe.","团队里弥漫着一种有害的氛围。","A noxious atmosphere reigned in the team."],
      ["Ces rumeurs ont un effet délétère.","这些谣言有毒害作用。","These rumours have a deleterious effect."],
      [{fr:"une influence délétère",zh:"毒害性的影响"}],""),
    w("c2_012",L4,"exégèse","n.f.","阴性名词","f","[ɛɡzeʒɛz]","📜",["诠释","解经"],["exegesis"],
      ["Son exégèse du texte est subtile.","他对文本的诠释很精妙。","His exegesis of the text is subtle."],
      ["Cette exégèse éclaire le poème.","这一诠释阐明了这首诗。","This exegesis illuminates the poem."],
      [{fr:"se livrer à l'exégèse",zh:"进行诠释"}],""),
    w("c2_013",L4,"velléité","n.f.","阴性名词","f","[veleite]","🌫️",["三分钟热度","微弱意愿"],["vague intention","half-hearted urge"],
      ["De simples velléités de réforme.","不过是些改革的空想罢了。","Mere half-hearted urges to reform."],
      ["Il n'a que des velléités d'écrire.","他不过是有点想写作的念头罢了。","He has only vague intentions of writing."],
      [{fr:"des velléités de",zh:"…的空想"}],""),
    w("c2_014",L4,"emphase","n.f.","阴性名词","f","[ɑ̃faz]","🎺",["夸张","浮夸"],["bombast","overemphasis"],
      ["Il parle avec emphase.","他说话很浮夸。","He speaks with bombast."],
      ["Le discours, plein d'emphase, sonnait faux.","那充满浮夸的演讲显得虚假。","The bombastic speech rang false."],
      [{fr:"parler avec emphase",zh:"夸张地说"}],""),
    w("c2_015",L4,"laconique","adj.","形容词",null,"[lakɔnik]","🤐",["简洁的","言简意赅的"],["laconic","terse"],
      ["Une réponse laconique et tranchante.","一个简洁而干脆的回答。","A laconic, cutting reply."],
      ["Son télégramme était laconique.","他的电报很简短。","His telegram was terse."],
      [{fr:"un ton laconique",zh:"简洁的语气"}],""),
    w("c2_016",L4,"sagacité","n.f.","阴性名词","f","[saɡasite]","🦉",["睿智","洞察力"],["sagacity","shrewdness"],
      ["Il a analysé la situation avec sagacité.","他睿智地分析了局势。","He analysed the situation with sagacity."],
      ["Sa sagacité lui a évité bien des pièges.","他的睿智让他避开了许多陷阱。","His shrewdness spared him many pitfalls."],
      [{fr:"faire preuve de sagacité",zh:"展现出睿智"}],""),
    w("c2_017",L4,"tergiverser","v.","动词",null,"[tɛʁʒivɛʁse]","🌀",["支吾","拖延推诿"],["to prevaricate","to dither"],
      ["Cesse de tergiverser et décide-toi.","别再推诿，快做决定。","Stop dithering and make up your mind."],
      ["Le gouvernement tergiverse depuis des mois.","政府已经推诿了好几个月。","The government has been prevaricating for months."],
      [{fr:"tergiverser sans fin",zh:"没完没了地推诿"}],""),
    w("c2_018",L4,"pusillanime","adj.","形容词",null,"[pyzilanim]","🐁",["胆小的","懦弱的"],["pusillanimous","faint-hearted"],
      ["Une attitude pusillanime devant le danger.","面对危险的一种懦弱态度。","A faint-hearted attitude in the face of danger."],
      ["Un chef pusillanime perd la confiance des siens.","懦弱的领导会失去下属的信任。","A pusillanimous leader loses his people's trust."],
      [{fr:"un chef pusillanime",zh:"懦弱的领导"}],""),
    w("c2_019",L4,"apophtegme","n.m.","阳性名词","m","[apɔftɛɡm]","💬",["格言","箴言"],["apothegm","maxim"],
      ["Il ponctue ses discours d'apophtegmes.","他的讲话中不时穿插格言。","He punctuates his speeches with apothegms."],
      ["Cet apophtegme résume toute sa pensée.","这句箴言概括了他的全部思想。","This maxim sums up his entire thought."],
      [{fr:"citer un apophtegme",zh:"引用格言"}],""),
    w("c2_020",L4,"éluder","v.","动词",null,"[elyde]","🙈",["回避","躲闪"],["to evade","to sidestep"],
      ["Le ministre a éludé la question.","部长回避了这个问题。","The minister evaded the question."],
      ["On ne peut pas éluder ce problème.","这个问题无法回避。","We can't sidestep this problem."],
      [{fr:"éluder une question",zh:"回避问题"}],"")
    ,
    w("b1_025",L1,"travailler","v.","动词",null,"[tʁavaje]","💼",["工作","劳动"],["to work"],
      ["Je travaille dans un bureau.","我在办公室工作。","I work in an office."],
      ["Elle travaille dur pour réussir.","她努力工作以求成功。","She works hard to succeed."],
      [{fr:"travailler dur",zh:"努力工作"}],""),
    w("b1_026",L1,"bureau","n.m.","阳性名词","m","[byʁo]","🏢",["办公室","办公桌"],["office","desk"],
      ["Mon bureau est au troisième étage.","我的办公室在三楼。","My office is on the third floor."],
      ["Range tes affaires sur le bureau.","把你的东西整理到桌上。","Tidy your things on the desk."],
      [{fr:"aller au bureau",zh:"去上班"}],"复数为 « bureaux »。"),
    w("b1_027",L1,"maison","n.f.","阴性名词","f","[mɛzɔ̃]","🏠",["房子","家"],["house","home"],
      ["Ils ont acheté une maison à la campagne.","他们在乡下买了一栋房子。","They bought a house in the countryside."],
      ["Je rentre à la maison à six heures.","我六点回家。","I go home at six o'clock."],
      [{fr:"à la maison",zh:"在家"}],""),
    w("b1_028",L1,"appartement","n.m.","阳性名词","m","[apaʁtəmɑ̃]","🏬",["公寓"],["flat","apartment"],
      ["Nous louons un petit appartement.","我们租了一间小公寓。","We rent a small flat."],
      ["Son appartement donne sur le parc.","他的公寓朝向公园。","His flat looks out onto the park."],
      [{fr:"louer un appartement",zh:"租公寓"}],""),
    w("b1_029",L1,"chambre","n.f.","阴性名词","f","[ʃɑ̃bʁ]","🛏️",["卧室","房间"],["bedroom","room"],
      ["Ma chambre est très lumineuse.","我的卧室很明亮。","My bedroom is very bright."],
      ["L'hôtel a une chambre libre.","酒店有一间空房。","The hotel has a free room."],
      [{fr:"une chambre d'hôtel",zh:"酒店房间"}],""),
    w("b1_030",L1,"ville","n.f.","阴性名词","f","[vil]","🏙️",["城市","市"],["city","town"],
      ["Lyon est une belle ville.","里昂是座美丽的城市。","Lyon is a beautiful city."],
      ["Je vais en ville faire des courses.","我进城去购物。","I'm going into town to shop."],
      [{fr:"le centre-ville",zh:"市中心"}],""),
    w("b1_031",L1,"quartier","n.m.","阳性名词","m","[kaʁtje]","🏘️",["街区","社区"],["neighbourhood","district"],
      ["J'habite dans un quartier calme.","我住在一个安静的街区。","I live in a quiet neighbourhood."],
      ["Ce quartier est très animé le soir.","这个街区晚上很热闹。","This district is very lively in the evening."],
      [{fr:"un quartier animé",zh:"热闹的街区"}],""),
    w("b1_032",L1,"rue","n.f.","阴性名词","f","[ʁy]","🛣️",["街道","马路"],["street"],
      ["La rue est pleine de monde.","街上挤满了人。","The street is full of people."],
      ["Traverse la rue au feu rouge.","在红灯处过马路。","Cross the street at the red light."],
      [{fr:"dans la rue",zh:"在街上"}],""),
    w("b1_033",L1,"magasin","n.m.","阳性名词","m","[maɡazɛ̃]","🏪",["商店"],["shop","store"],
      ["Le magasin ferme à vingt heures.","商店晚上八点关门。","The shop closes at eight."],
      ["Il y a un nouveau magasin de chaussures.","有一家新的鞋店。","There's a new shoe shop."],
      [{fr:"un grand magasin",zh:"百货商店"}],""),
    w("b1_034",L1,"marché","n.m.","阳性名词","m","[maʁʃe]","🧺",["市场","集市"],["market"],
      ["On achète des légumes au marché.","我们在市场买蔬菜。","We buy vegetables at the market."],
      ["Le marché a lieu le dimanche matin.","集市在周日早上举行。","The market takes place on Sunday morning."],
      [{fr:"aller au marché",zh:"去市场"}],""),
    w("b1_035",L1,"acheter","v.","动词",null,"[aʃte]","🛒",["买","购买"],["to buy"],
      ["Je voudrais acheter du pain.","我想买点面包。","I'd like to buy some bread."],
      ["Elle a acheté un cadeau pour sa mère.","她给妈妈买了一份礼物。","She bought a gift for her mother."],
      [{fr:"acheter en solde",zh:"打折时购买"}],"« acheter »（买）≠ « vendre »（卖）。"),
    w("b1_036",L1,"vendre","v.","动词",null,"[vɑ̃dʁ]","🏷️",["卖","出售"],["to sell"],
      ["Ils vendent des fruits frais.","他们卖新鲜水果。","They sell fresh fruit."],
      ["J'ai vendu ma vieille voiture.","我卖掉了我的旧车。","I sold my old car."],
      [{fr:"vendre à bas prix",zh:"低价出售"}],""),
    w("b1_037",L1,"payer","v.","动词",null,"[peje]","💳",["付款","支付"],["to pay"],
      ["Je peux payer par carte ?","我可以刷卡付款吗？","Can I pay by card?"],
      ["Il a payé l'addition.","他付了账单。","He paid the bill."],
      [{fr:"payer en espèces",zh:"用现金支付"}],""),
    w("b1_038",L1,"prix","n.m.","阳性名词","m","[pʁi]","🏷️",["价格","价钱"],["price"],
      ["Quel est le prix de ce manteau ?","这件大衣多少钱？","What's the price of this coat?"],
      ["Les prix ont beaucoup augmenté.","价格上涨了很多。","Prices have risen a lot."],
      [{fr:"à moitié prix",zh:"半价"}],""),
    w("b1_039",L1,"cher","adj.","形容词",null,"[ʃɛʁ]","💸",["贵的","昂贵的"],["expensive","dear"],
      ["Ce restaurant est trop cher.","这家餐厅太贵了。","This restaurant is too expensive."],
      ["La vie est chère dans les grandes villes.","大城市生活费很高。","Life is expensive in big cities."],
      [{fr:"coûter cher",zh:"很贵"}],"阴性形式为 « chère »。"),
    w("b1_040",L1,"gratuit","adj.","形容词",null,"[ɡʁatɥi]","🆓",["免费的"],["free (of charge)"],
      ["L'entrée du musée est gratuite.","博物馆入场免费。","Museum entry is free."],
      ["Ce logiciel est gratuit.","这个软件是免费的。","This software is free."],
      [{fr:"gratuit pour les enfants",zh:"儿童免费"}],"阴性形式为 « gratuite »。"),
    w("b1_041",L1,"nourriture","n.f.","阴性名词","f","[nuʁityʁ]","🍲",["食物"],["food"],
      ["La nourriture est délicieuse ici.","这里的食物很美味。","The food is delicious here."],
      ["Il faut acheter de la nourriture pour la semaine.","得买够一周的食物。","We must buy food for the week."],
      [{fr:"la nourriture saine",zh:"健康食物"}],""),
    w("b1_042",L1,"repas","n.m.","阳性名词","m","[ʁəpa]","🍽️",["餐","一顿饭"],["meal"],
      ["Le repas est prêt !","饭做好了！","The meal is ready!"],
      ["Nous prenons trois repas par jour.","我们一天吃三顿饭。","We have three meals a day."],
      [{fr:"préparer le repas",zh:"准备饭菜"}],""),
    w("b1_043",L1,"boisson","n.f.","阴性名词","f","[bwasɔ̃]","🥤",["饮料"],["drink","beverage"],
      ["Quelle boisson veux-tu ?","你想喝什么？","Which drink do you want?"],
      ["Les boissons sont au frais.","饮料在冰箱里。","The drinks are chilling."],
      [{fr:"une boisson fraîche",zh:"冰镇饮料"}],""),
    w("b1_044",L1,"légume","n.m.","阳性名词","m","[leɡym]","🥕",["蔬菜"],["vegetable"],
      ["Mange tes légumes !","把你的蔬菜吃掉！","Eat your vegetables!"],
      ["Les légumes verts sont bons pour la santé.","绿色蔬菜有益健康。","Green vegetables are good for you."],
      [{fr:"des légumes frais",zh:"新鲜蔬菜"}],""),
    w("b1_045",L1,"fruit","n.m.","阳性名词","m","[fʁɥi]","🍎",["水果"],["fruit"],
      ["Je mange un fruit chaque matin.","我每天早上吃一个水果。","I eat a piece of fruit every morning."],
      ["Les fruits d'été sont sucrés.","夏天的水果很甜。","Summer fruits are sweet."],
      [{fr:"un jus de fruit",zh:"果汁"}],""),
    w("b1_046",L1,"viande","n.f.","阴性名词","f","[vjɑ̃d]","🥩",["肉"],["meat"],
      ["Je ne mange pas de viande.","我不吃肉。","I don't eat meat."],
      ["La viande est bien cuite.","肉煮得很熟。","The meat is well cooked."],
      [{fr:"de la viande rouge",zh:"红肉"}],""),
    w("b1_047",L1,"pain","n.m.","阳性名词","m","[pɛ̃]","🥖",["面包"],["bread"],
      ["J'achète du pain à la boulangerie.","我在面包店买面包。","I buy bread at the bakery."],
      ["Ce pain est encore chaud.","这面包还是热的。","This bread is still warm."],
      [{fr:"un morceau de pain",zh:"一块面包"}],""),
    w("b1_048",L1,"fromage","n.m.","阳性名词","m","[fʁɔmaʒ]","🧀",["奶酪"],["cheese"],
      ["La France produit beaucoup de fromages.","法国生产很多种奶酪。","France produces many cheeses."],
      ["Tu veux du fromage après le repas ?","饭后你想吃点奶酪吗？","Do you want some cheese after the meal?"],
      [{fr:"un plateau de fromages",zh:"奶酪拼盘"}],""),
    w("b1_049",L1,"cuisiner","v.","动词",null,"[kɥizine]","👨‍🍳",["做饭","烹饪"],["to cook"],
      ["J'aime cuisiner le week-end.","我喜欢周末做饭。","I like to cook at the weekend."],
      ["Elle cuisine un plat italien ce soir.","她今晚做一道意大利菜。","She's cooking an Italian dish tonight."],
      [{fr:"cuisiner un plat",zh:"做一道菜"}],""),
    w("b1_050",L1,"voiture","n.f.","阴性名词","f","[vwatyʁ]","🚗",["汽车","轿车"],["car"],
      ["Ma voiture est en panne.","我的车坏了。","My car has broken down."],
      ["On y va en voiture ou à pied ?","我们开车还是走路去？","Shall we go by car or on foot?"],
      [{fr:"conduire une voiture",zh:"开车"}],""),
    w("b1_051",L1,"train","n.m.","阳性名词","m","[tʁɛ̃]","🚆",["火车"],["train"],
      ["Le train pour Paris part à midi.","去巴黎的火车中午出发。","The train to Paris leaves at noon."],
      ["Nous avons raté le train.","我们错过了火车。","We missed the train."],
      [{fr:"prendre le train",zh:"坐火车"}],""),
    w("b1_052",L1,"avion","n.m.","阳性名词","m","[avjɔ̃]","✈️",["飞机"],["plane","aeroplane"],
      ["L'avion décolle dans une heure.","飞机一小时后起飞。","The plane takes off in an hour."],
      ["Je voyage rarement en avion.","我很少坐飞机旅行。","I rarely travel by plane."],
      [{fr:"prendre l'avion",zh:"乘飞机"}],""),
    w("b1_053",L1,"billet","n.m.","阳性名词","m","[bijɛ]","🎫",["票","钞票"],["ticket","banknote"],
      ["J'ai réservé un billet de train.","我订了一张火车票。","I booked a train ticket."],
      ["Il paie avec un billet de vingt euros.","他用一张二十欧元的钞票付款。","He pays with a twenty-euro note."],
      [{fr:"un billet aller-retour",zh:"往返票"}],""),
    w("b1_054",L1,"conduire","v.","动词",null,"[kɔ̃dɥiʁ]","🚘",["驾驶","开车"],["to drive"],
      ["Il apprend à conduire.","他在学开车。","He's learning to drive."],
      ["Conduis prudemment !","小心驾驶！","Drive carefully!"],
      [{fr:"un permis de conduire",zh:"驾照"}],""),
    w("b1_055",L1,"arriver","v.","动词",null,"[aʁive]","🛬",["到达","抵达"],["to arrive","to happen"],
      ["Le bus arrive dans cinq minutes.","公交车五分钟后到。","The bus arrives in five minutes."],
      ["Qu'est-ce qui est arrivé ?","发生了什么事？","What happened?"],
      [{fr:"arriver à l'heure",zh:"准时到达"}],""),
    w("b1_056",L1,"partir","v.","动词",null,"[paʁtiʁ]","🚶",["离开","出发"],["to leave","to go"],
      ["Nous partons demain matin.","我们明天早上出发。","We're leaving tomorrow morning."],
      ["Elle est partie sans dire au revoir.","她没说再见就走了。","She left without saying goodbye."],
      [{fr:"partir en vacances",zh:"去度假"}],""),
    w("b1_057",L1,"rester","v.","动词",null,"[ʁɛste]","🪑",["留下","停留"],["to stay","to remain"],
      ["Je reste à la maison ce soir.","我今晚待在家里。","I'm staying home tonight."],
      ["Il reste encore du travail.","还剩下一些工作。","There's still some work left."],
      [{fr:"rester calme",zh:"保持冷静"}],""),
    w("b1_058",L1,"attendre","v.","动词",null,"[atɑ̃dʁ]","⏳",["等待","等候"],["to wait","to expect"],
      ["Attends-moi une minute !","等我一下！","Wait for me a minute!"],
      ["Nous attendons le résultat.","我们在等结果。","We're waiting for the result."],
      [{fr:"attendre le bus",zh:"等公交"}],""),
    w("b1_059",L1,"chercher","v.","动词",null,"[ʃɛʁʃe]","🔎",["寻找","找"],["to look for","to fetch"],
      ["Je cherche mes clés.","我在找我的钥匙。","I'm looking for my keys."],
      ["Il va chercher les enfants à l'école.","他去学校接孩子。","He's fetching the children from school."],
      [{fr:"chercher du travail",zh:"找工作"}],""),
    w("b1_060",L1,"trouver","v.","动词",null,"[tʁuve]","🎯",["找到","认为"],["to find","to think"],
      ["J'ai trouvé un bon restaurant.","我找到了一家好餐厅。","I found a good restaurant."],
      ["Je trouve ce film ennuyeux.","我觉得这部电影很无聊。","I find this film boring."],
      [{fr:"trouver une solution",zh:"找到解决办法"}],""),
    w("b1_061",L1,"perdre","v.","动词",null,"[pɛʁdʁ]","🫤",["失去","丢失","输"],["to lose"],
      ["J'ai perdu mon parapluie.","我把伞弄丢了。","I've lost my umbrella."],
      ["Notre équipe a perdu le match.","我们队输了比赛。","Our team lost the match."],
      [{fr:"perdre du temps",zh:"浪费时间"}],""),
    w("b1_062",L1,"porte","n.f.","阴性名词","f","[pɔʁt]","🚪",["门"],["door"],
      ["Ferme la porte, s'il te plaît.","请把门关上。","Close the door, please."],
      ["Quelqu'un frappe à la porte.","有人在敲门。","Someone is knocking at the door."],
      [{fr:"ouvrir la porte",zh:"开门"}],""),
    w("b1_063",L1,"fenêtre","n.f.","阴性名词","f","[fənɛtʁ]","🪟",["窗户"],["window"],
      ["Ouvre la fenêtre, il fait chaud.","开窗吧，天气很热。","Open the window, it's hot."],
      ["La fenêtre donne sur la mer.","窗户面朝大海。","The window looks out onto the sea."],
      [{fr:"regarder par la fenêtre",zh:"看向窗外"}],""),
    w("b1_064",L1,"école","n.f.","阴性名词","f","[ekɔl]","🏫",["学校"],["school"],
      ["Les enfants vont à l'école à pied.","孩子们走路去上学。","The children walk to school."],
      ["Cette école est réputée.","这所学校很有名。","This school is well known."],
      [{fr:"aller à l'école",zh:"上学"}],""),
    w("b1_065",L1,"apprendre","v.","动词",null,"[apʁɑ̃dʁ]","📚",["学习","学会"],["to learn"],
      ["J'apprends le français depuis deux ans.","我学法语两年了。","I've been learning French for two years."],
      ["Il apprend vite.","他学得很快。","He learns fast."],
      [{fr:"apprendre par cœur",zh:"背诵记住"}],""),
    w("b1_066",L1,"comprendre","v.","动词",null,"[kɔ̃pʁɑ̃dʁ]","🧠",["理解","懂"],["to understand"],
      ["Je ne comprends pas la question.","我不明白这个问题。","I don't understand the question."],
      ["Tu comprends le chinois ?","你懂中文吗？","Do you understand Chinese?"],
      [{fr:"se faire comprendre",zh:"让人听懂"}],""),
    w("b1_067",L1,"expliquer","v.","动词",null,"[ɛksplike]","🗣️",["解释","说明"],["to explain"],
      ["Peux-tu m'expliquer la règle ?","你能给我解释一下规则吗？","Can you explain the rule to me?"],
      ["Le professeur explique la leçon.","老师在讲解课程。","The teacher explains the lesson."],
      [{fr:"expliquer un problème",zh:"说明一个问题"}],""),
    w("b1_068",L1,"question","n.f.","阴性名词","f","[kɛstjɔ̃]","❓",["问题"],["question"],
      ["J'ai une question à poser.","我有一个问题要问。","I have a question to ask."],
      ["Sa question est très pertinente.","他的问题很中肯。","His question is very relevant."],
      [{fr:"poser une question",zh:"提问"}],"")
    ,
    w("b1_069",L1,"corps","n.m.","阳性名词","m","[kɔʁ]","🧍",["身体"],["body"],
      ["Le sport est bon pour le corps.","运动对身体有益。","Exercise is good for the body."],
      ["Il a mal partout dans le corps.","他浑身疼。","His whole body aches."],
      [{fr:"le corps humain",zh:"人体"}],""),
    w("b1_070",L1,"tête","n.f.","阴性名词","f","[tɛt]","🙂",["头","脑袋"],["head"],
      ["J'ai mal à la tête.","我头疼。","I have a headache."],
      ["Il a une idée en tête.","他心里有个主意。","He has an idea in mind."],
      [{fr:"de la tête aux pieds",zh:"从头到脚"}],""),
    w("b1_071",L1,"main","n.f.","阴性名词","f","[mɛ̃]","✋",["手"],["hand"],
      ["Lave-toi les mains avant de manger.","吃饭前洗手。","Wash your hands before eating."],
      ["Ils se donnent la main.","他们手牵手。","They hold hands."],
      [{fr:"serrer la main",zh:"握手"}],""),
    w("b1_072",L1,"pied","n.m.","阳性名词","m","[pje]","🦶",["脚"],["foot"],
      ["J'y vais à pied.","我走着去。","I'm going on foot."],
      ["Il s'est fait mal au pied.","他把脚弄伤了。","He hurt his foot."],
      [{fr:"aller à pied",zh:"步行"}],""),
    w("b1_073",L1,"cœur","n.m.","阳性名词","m","[kœʁ]","❤️",["心","心脏"],["heart"],
      ["Son cœur bat vite.","他的心跳得很快。","His heart is beating fast."],
      ["Elle a bon cœur.","她心地善良。","She has a kind heart."],
      [{fr:"apprendre par cœur",zh:"背下来"}],""),
    w("b1_074",L1,"malade","adj.","形容词",null,"[malad]","🤒",["生病的","病的"],["ill","sick"],
      ["Je suis malade depuis hier.","我从昨天起就病了。","I've been ill since yesterday."],
      ["Il est trop malade pour travailler.","他病得不能工作。","He's too ill to work."],
      [{fr:"tomber malade",zh:"生病"}],""),
    w("b1_075",L1,"médecin","n.m.","阳性名词","m","[medsɛ̃]","🩺",["医生"],["doctor"],
      ["Je dois voir un médecin.","我得去看医生。","I need to see a doctor."],
      ["Le médecin m'a examiné.","医生给我做了检查。","The doctor examined me."],
      [{fr:"aller chez le médecin",zh:"去看医生"}],""),
    w("b1_076",L1,"médicament","n.m.","阳性名词","m","[medikamɑ̃]","💊",["药","药物"],["medicine","drug"],
      ["Prends ce médicament trois fois par jour.","这种药每天吃三次。","Take this medicine three times a day."],
      ["Ce médicament est sans ordonnance.","这种药不需要处方。","This medicine is over the counter."],
      [{fr:"prendre un médicament",zh:"服药"}],""),
    w("b1_077",L1,"douleur","n.f.","阴性名词","f","[dulœʁ]","😣",["疼痛","痛苦"],["pain"],
      ["Je ressens une douleur au dos.","我感觉背痛。","I feel a pain in my back."],
      ["La douleur a disparu.","疼痛消失了。","The pain has gone."],
      [{fr:"soulager la douleur",zh:"缓解疼痛"}],""),
    w("b1_078",L1,"guérir","v.","动词",null,"[ɡeʁiʁ]","🩹",["治愈","痊愈"],["to heal","to recover"],
      ["Le malade est vite guéri.","病人很快痊愈了。","The patient recovered quickly."],
      ["Ce remède guérit la toux.","这个方子能治咳嗽。","This remedy heals a cough."],
      [{fr:"guérir d'une maladie",zh:"从疾病中康复"}],""),
    w("b1_079",L1,"dormir","v.","动词",null,"[dɔʁmiʁ]","😴",["睡觉","睡"],["to sleep"],
      ["Je dors huit heures par nuit.","我每晚睡八小时。","I sleep eight hours a night."],
      ["Les enfants dorment déjà.","孩子们已经睡了。","The children are already asleep."],
      [{fr:"dormir profondément",zh:"熟睡"}],""),
    w("b1_080",L1,"se reposer","v.","动词","","[sə ʁəpoze]","🛌",["休息"],["to rest"],
      ["Repose-toi bien ce week-end.","这个周末好好休息。","Rest well this weekend."],
      ["Après l'effort, il faut se reposer.","运动后需要休息。","After exercise, you need to rest."],
      [{fr:"se reposer un peu",zh:"休息一会儿"}],""),
    w("b1_081",L1,"heure","n.f.","阴性名词","f","[œʁ]","🕐",["小时","钟点"],["hour","time"],
      ["Quelle heure est-il ?","现在几点？","What time is it?"],
      ["Le film dure deux heures.","电影时长两小时。","The film lasts two hours."],
      [{fr:"à l'heure",zh:"准时"}],""),
    w("b1_082",L1,"jour","n.m.","阳性名词","m","[ʒuʁ]","☀️",["天","白天"],["day"],
      ["Il pleut depuis trois jours.","已经下了三天雨。","It has been raining for three days."],
      ["Quel jour sommes-nous ?","今天星期几？","What day is it?"],
      [{fr:"tous les jours",zh:"每天"}],""),
    w("b1_083",L1,"semaine","n.f.","阴性名词","f","[səmɛn]","📆",["星期","周"],["week"],
      ["Je travaille cinq jours par semaine.","我一周工作五天。","I work five days a week."],
      ["On se voit la semaine prochaine.","我们下周见。","See you next week."],
      [{fr:"en semaine",zh:"在工作日"}],""),
    w("b1_084",L1,"mois","n.m.","阳性名词","m","[mwa]","🗓️",["月","月份"],["month"],
      ["Le loyer est payé chaque mois.","房租每月支付。","The rent is paid each month."],
      ["Je pars en vacances le mois prochain.","我下个月去度假。","I'm going on holiday next month."],
      [{fr:"ce mois-ci",zh:"这个月"}],""),
    w("b1_085",L1,"année","n.f.","阴性名词","f","[ane]","📅",["年"],["year"],
      ["Bonne année !","新年快乐！","Happy New Year!"],
      ["Cette année a été difficile.","这一年很艰难。","This year has been hard."],
      [{fr:"toute l'année",zh:"一整年"}],""),
    w("b1_086",L1,"matin","n.m.","阳性名词","m","[matɛ̃]","🌅",["早晨","上午"],["morning"],
      ["Je me lève tôt le matin.","我早上起得早。","I get up early in the morning."],
      ["Ce matin, il fait beau.","今天早上天气很好。","This morning the weather is nice."],
      [{fr:"du matin au soir",zh:"从早到晚"}],""),
    w("b1_087",L1,"soir","n.m.","阳性名词","m","[swaʁ]","🌆",["晚上","傍晚"],["evening"],
      ["On dîne à sept heures du soir.","我们晚上七点吃晚饭。","We have dinner at seven in the evening."],
      ["À ce soir !","晚上见！","See you tonight!"],
      [{fr:"hier soir",zh:"昨晚"}],""),
    w("b1_088",L1,"tôt","adv.","副词",null,"[to]","⏰",["早"],["early"],
      ["Tu es arrivé trop tôt.","你来得太早了。","You arrived too early."],
      ["Il se couche tôt.","他睡得早。","He goes to bed early."],
      [{fr:"plus tôt",zh:"更早"}],"« tôt »（早）≠ « tard »（晚）。"),
    w("b1_089",L1,"tard","adv.","副词",null,"[taʁ]","🌙",["晚","迟"],["late"],
      ["Il est déjà tard, rentrons.","已经很晚了，回家吧。","It's already late, let's go home."],
      ["Mieux vaut tard que jamais.","迟做总比不做好。","Better late than never."],
      [{fr:"plus tard",zh:"晚点"}],""),
    w("b1_090",L1,"pluie","n.f.","阴性名词","f","[plɥi]","🌧️",["雨"],["rain"],
      ["La pluie tombe fort.","雨下得很大。","The rain is falling hard."],
      ["On sort malgré la pluie.","尽管下雨我们还是出门。","We're going out despite the rain."],
      [{fr:"sous la pluie",zh:"在雨中"}],""),
    w("b1_091",L1,"neige","n.f.","阴性名词","f","[nɛʒ]","❄️",["雪"],["snow"],
      ["Les enfants jouent dans la neige.","孩子们在雪里玩。","The children play in the snow."],
      ["La neige recouvre les montagnes.","雪覆盖了群山。","Snow covers the mountains."],
      [{fr:"un bonhomme de neige",zh:"雪人"}],""),
    w("b1_092",L1,"soleil","n.m.","阳性名词","m","[sɔlɛj]","☀️",["太阳","阳光"],["sun"],
      ["Il y a du soleil aujourd'hui.","今天有太阳。","It's sunny today."],
      ["Le soleil se couche à l'ouest.","太阳在西边落下。","The sun sets in the west."],
      [{fr:"un coup de soleil",zh:"晒伤"}],""),
    w("b1_093",L1,"vent","n.m.","阳性名词","m","[vɑ̃]","💨",["风"],["wind"],
      ["Le vent souffle fort.","风刮得很大。","The wind is blowing hard."],
      ["Il y a beaucoup de vent sur la côte.","海岸上风很大。","It's very windy on the coast."],
      [{fr:"un coup de vent",zh:"一阵风"}],""),
    w("b1_094",L1,"chaud","adj.","形容词",null,"[ʃo]","🥵",["热的","暖的"],["hot","warm"],
      ["Le café est encore chaud.","咖啡还是热的。","The coffee is still hot."],
      ["Il fait très chaud en été.","夏天很热。","It's very hot in summer."],
      [{fr:"avoir chaud",zh:"觉得热"}],"阴性形式为 « chaude »。"),
    w("b1_095",L1,"froid","adj.","形容词",null,"[fʁwa]","🥶",["冷的"],["cold"],
      ["L'eau est trop froide.","水太冷了。","The water is too cold."],
      ["Il fait froid dehors.","外面很冷。","It's cold outside."],
      [{fr:"avoir froid",zh:"觉得冷"}],"阴性形式为 « froide »。"),
    w("b1_096",L1,"vêtement","n.m.","阳性名词","m","[vɛtmɑ̃]","👕",["衣服","服装"],["clothing","garment"],
      ["Je range mes vêtements dans l'armoire.","我把衣服放进衣柜。","I put my clothes in the wardrobe."],
      ["Prends des vêtements chauds.","带上保暖的衣服。","Take some warm clothes."],
      [{fr:"des vêtements chauds",zh:"保暖的衣服"}],""),
    w("b1_097",L1,"chaussure","n.f.","阴性名词","f","[ʃosyʁ]","👟",["鞋"],["shoe"],
      ["Ces chaussures sont confortables.","这双鞋很舒服。","These shoes are comfortable."],
      ["Mets tes chaussures, on part.","穿上鞋，我们走了。","Put on your shoes, we're leaving."],
      [{fr:"une paire de chaussures",zh:"一双鞋"}],""),
    w("b1_098",L1,"manteau","n.m.","阳性名词","m","[mɑ̃to]","🧥",["大衣","外套"],["coat"],
      ["Mets ton manteau, il fait froid.","穿上外套，天冷。","Put on your coat, it's cold."],
      ["J'ai acheté un manteau d'hiver.","我买了一件冬季大衣。","I bought a winter coat."],
      [{fr:"un manteau chaud",zh:"暖和的大衣"}],"复数为 « manteaux »。"),
    w("b1_099",L1,"porter","v.","动词",null,"[pɔʁte]","🎒",["穿","携带","拿"],["to wear","to carry"],
      ["Elle porte une robe rouge.","她穿着一条红裙子。","She's wearing a red dress."],
      ["Il porte une valise lourde.","他提着一个沉重的行李箱。","He's carrying a heavy suitcase."],
      [{fr:"porter des lunettes",zh:"戴眼镜"}],""),
    w("b1_100",L1,"peur","n.f.","阴性名词","f","[pœʁ]","😨",["害怕","恐惧"],["fear"],
      ["Il a peur des chiens.","他怕狗。","He's afraid of dogs."],
      ["N'aie pas peur !","别害怕！","Don't be afraid!"],
      [{fr:"avoir peur",zh:"害怕"}],""),
    w("b1_101",L1,"colère","n.f.","阴性名词","f","[kɔlɛʁ]","😠",["愤怒","生气"],["anger"],
      ["Il est en colère contre moi.","他在生我的气。","He's angry with me."],
      ["Sa colère est passée.","他的怒气消了。","His anger has passed."],
      [{fr:"se mettre en colère",zh:"发火"}],""),
    w("b1_102",L1,"rire","v.","动词",null,"[ʁiʁ]","😂",["笑","大笑"],["to laugh"],
      ["Nous avons beaucoup ri.","我们笑得很开心。","We laughed a lot."],
      ["Ne ris pas de lui.","别嘲笑他。","Don't laugh at him."],
      [{fr:"éclater de rire",zh:"放声大笑"}],""),
    w("b1_103",L1,"pleurer","v.","动词",null,"[pløʁe]","😢",["哭","流泪"],["to cry"],
      ["Le bébé pleure la nuit.","婴儿夜里哭。","The baby cries at night."],
      ["Elle a pleuré de joie.","她高兴得哭了。","She cried with joy."],
      [{fr:"pleurer de joie",zh:"喜极而泣"}],""),
    w("b1_104",L1,"sourire","v.","动词",null,"[suʁiʁ]","😊",["微笑"],["to smile"],
      ["Elle sourit à tout le monde.","她对每个人微笑。","She smiles at everyone."],
      ["Souris pour la photo !","拍照笑一个！","Smile for the photo!"],
      [{fr:"un large sourire",zh:"灿烂的微笑"}],"亦作阳性名词 « un sourire »（微笑）。"),
    w("b1_105",L1,"aimer","v.","动词",null,"[eme]","😍",["爱","喜欢"],["to love","to like"],
      ["J'aime beaucoup la musique.","我很喜欢音乐。","I like music a lot."],
      ["Ils s'aiment depuis dix ans.","他们相爱十年了。","They've loved each other for ten years."],
      [{fr:"aimer bien",zh:"挺喜欢"}],""),
    w("b1_106",L1,"détester","v.","动词",null,"[detɛste]","😖",["讨厌","憎恨"],["to hate"],
      ["Je déteste attendre.","我讨厌等待。","I hate waiting."],
      ["Il déteste le froid.","他讨厌寒冷。","He hates the cold."],
      [{fr:"détester quelque chose",zh:"讨厌某物"}],""),
    w("b1_107",L1,"espérer","v.","动词",null,"[ɛspeʁe]","🤞",["希望","期望"],["to hope"],
      ["J'espère te revoir bientôt.","我希望很快再见到你。","I hope to see you again soon."],
      ["Nous espérons qu'il fera beau.","我们希望天气会好。","We hope the weather will be nice."],
      [{fr:"espérer que",zh:"希望…"}],""),
    w("b1_108",L1,"parler","v.","动词",null,"[paʁle]","💬",["说话","讲"],["to speak","to talk"],
      ["Elle parle trois langues.","她会说三种语言。","She speaks three languages."],
      ["On peut parler une minute ?","我们能聊一分钟吗？","Can we talk for a minute?"],
      [{fr:"parler fort",zh:"大声说话"}],""),
    w("b1_109",L1,"écouter","v.","动词",null,"[ekute]","👂",["听","倾听"],["to listen"],
      ["J'écoute de la musique en marchant.","我边走边听音乐。","I listen to music while walking."],
      ["Écoute bien la consigne.","仔细听指示。","Listen carefully to the instruction."],
      [{fr:"écouter la radio",zh:"听广播"}],""),
    w("b1_110",L1,"lire","v.","动词",null,"[liʁ]","📖",["读","阅读"],["to read"],
      ["Je lis un roman en ce moment.","我最近在读一本小说。","I'm reading a novel at the moment."],
      ["Il lit le journal chaque matin.","他每天早上读报纸。","He reads the newspaper every morning."],
      [{fr:"lire à voix haute",zh:"朗读"}],""),
    w("b1_111",L1,"écrire","v.","动词",null,"[ekʁiʁ]","✍️",["写","书写"],["to write"],
      ["Écris ton nom ici.","把你的名字写在这里。","Write your name here."],
      ["Elle écrit des lettres à sa famille.","她给家人写信。","She writes letters to her family."],
      [{fr:"écrire une lettre",zh:"写信"}],""),
    w("b1_112",L1,"langue","n.f.","阴性名词","f","[lɑ̃ɡ]","👅",["语言","舌头"],["language","tongue"],
      ["Le français est une belle langue.","法语是一门优美的语言。","French is a beautiful language."],
      ["Combien de langues parles-tu ?","你会说几种语言？","How many languages do you speak?"],
      [{fr:"une langue étrangère",zh:"外语"}],"")
    ,
    w("b1_113",L1,"nature","n.f.","阴性名词","f","[natyʁ]","🌿",["大自然","自然"],["nature"],
      ["J'aime me promener dans la nature.","我喜欢在大自然中散步。","I like to walk in nature."],
      ["Il faut respecter la nature.","应该尊重自然。","We must respect nature."],
      [{fr:"en pleine nature",zh:"在大自然中"}],""),
    w("b1_114",L1,"arbre","n.m.","阳性名词","m","[aʁbʁ]","🌳",["树"],["tree"],
      ["Cet arbre est très vieux.","这棵树很老了。","This tree is very old."],
      ["Les oiseaux chantent dans les arbres.","鸟儿在树上歌唱。","The birds sing in the trees."],
      [{fr:"planter un arbre",zh:"种树"}],""),
    w("b1_115",L1,"fleur","n.f.","阴性名词","f","[flœʁ]","🌸",["花"],["flower"],
      ["Elle offre des fleurs à sa mère.","她给妈妈送花。","She gives flowers to her mother."],
      ["Les fleurs sentent bon.","花闻起来很香。","The flowers smell nice."],
      [{fr:"un bouquet de fleurs",zh:"一束花"}],""),
    w("b1_116",L1,"rivière","n.f.","阴性名词","f","[ʁivjɛʁ]","🏞️",["河","河流"],["river"],
      ["Les enfants jouent près de la rivière.","孩子们在河边玩。","The children play by the river."],
      ["La rivière traverse le village.","河流穿过村庄。","The river runs through the village."],
      [{fr:"au bord de la rivière",zh:"在河边"}],""),
    w("b1_117",L1,"mer","n.f.","阴性名词","f","[mɛʁ]","🌊",["海","大海"],["sea"],
      ["Nous allons à la mer cet été.","今年夏天我们去海边。","We're going to the sea this summer."],
      ["La mer est calme aujourd'hui.","今天海面很平静。","The sea is calm today."],
      [{fr:"au bord de la mer",zh:"在海边"}],""),
    w("b1_118",L1,"montagne","n.f.","阴性名词","f","[mɔ̃taɲ]","⛰️",["山","高山"],["mountain"],
      ["Ils font de la randonnée en montagne.","他们在山里徒步。","They go hiking in the mountains."],
      ["La montagne est couverte de neige.","山上覆盖着雪。","The mountain is covered with snow."],
      [{fr:"à la montagne",zh:"在山里"}],""),
    w("b1_119",L1,"forêt","n.f.","阴性名词","f","[fɔʁɛ]","🌲",["森林"],["forest"],
      ["On se promène dans la forêt.","我们在森林里散步。","We walk in the forest."],
      ["La forêt est pleine d'animaux.","森林里有很多动物。","The forest is full of animals."],
      [{fr:"une forêt dense",zh:"茂密的森林"}],""),
    w("b1_120",L1,"animal","n.m.","阳性名词","m","[animal]","🐾",["动物"],["animal"],
      ["Le chien est un animal fidèle.","狗是忠诚的动物。","The dog is a loyal animal."],
      ["Il protège les animaux sauvages.","他保护野生动物。","He protects wild animals."],
      [{fr:"un animal domestique",zh:"家养动物"}],"复数为 « animaux »。"),
    w("b1_121",L1,"chien","n.m.","阳性名词","m","[ʃjɛ̃]","🐕",["狗"],["dog"],
      ["Mon chien s'appelle Max.","我的狗叫马克斯。","My dog is called Max."],
      ["Le chien aboie dans le jardin.","狗在院子里叫。","The dog barks in the garden."],
      [{fr:"promener le chien",zh:"遛狗"}],""),
    w("b1_122",L1,"chat","n.m.","阳性名词","m","[ʃa]","🐈",["猫"],["cat"],
      ["Le chat dort sur le canapé.","猫睡在沙发上。","The cat sleeps on the sofa."],
      ["Elle a adopté un petit chat.","她领养了一只小猫。","She adopted a kitten."],
      [{fr:"un chat noir",zh:"黑猫"}],""),
    w("b1_123",L1,"oiseau","n.m.","阳性名词","m","[wazo]","🐦",["鸟"],["bird"],
      ["Un oiseau chante sur le toit.","一只鸟在屋顶上唱歌。","A bird sings on the roof."],
      ["Les oiseaux migrent en hiver.","鸟儿在冬天迁徙。","Birds migrate in winter."],
      [{fr:"un nid d'oiseau",zh:"鸟巢"}],"复数为 « oiseaux »。"),
    w("b1_124",L1,"poisson","n.m.","阳性名词","m","[pwasɔ̃]","🐟",["鱼"],["fish"],
      ["On mange du poisson le vendredi.","我们周五吃鱼。","We eat fish on Fridays."],
      ["Il y a des poissons dans l'étang.","池塘里有鱼。","There are fish in the pond."],
      [{fr:"pêcher un poisson",zh:"钓鱼"}],""),
    w("b1_125",L1,"jardin","n.m.","阳性名词","m","[ʒaʁdɛ̃]","🌻",["花园","院子"],["garden"],
      ["Ils cultivent des tomates dans le jardin.","他们在花园里种番茄。","They grow tomatoes in the garden."],
      ["Le jardin est plein de fleurs.","花园里满是鲜花。","The garden is full of flowers."],
      [{fr:"un jardin public",zh:"公园"}],""),
    w("b1_126",L1,"plage","n.f.","阴性名词","f","[plaʒ]","🏖️",["海滩","沙滩"],["beach"],
      ["Nous passons la journée à la plage.","我们在海滩上度过一天。","We spend the day at the beach."],
      ["La plage est bondée en août.","八月海滩上人很多。","The beach is crowded in August."],
      [{fr:"une serviette de plage",zh:"沙滩巾"}],""),
    w("b1_127",L1,"loisir","n.m.","阳性名词","m","[lwaziʁ]","🎨",["休闲","业余爱好"],["leisure","hobby"],
      ["La lecture est mon loisir préféré.","阅读是我最喜欢的爱好。","Reading is my favourite hobby."],
      ["Il a peu de temps pour les loisirs.","他很少有空闲时间。","He has little time for leisure."],
      [{fr:"un centre de loisirs",zh:"休闲中心"}],""),
    w("b1_128",L1,"sport","n.m.","阳性名词","m","[spɔʁ]","⚽",["运动","体育"],["sport"],
      ["Je fais du sport trois fois par semaine.","我一周运动三次。","I do sport three times a week."],
      ["Le football est un sport populaire.","足球是一项受欢迎的运动。","Football is a popular sport."],
      [{fr:"faire du sport",zh:"做运动"}],""),
    w("b1_129",L1,"jouer","v.","动词",null,"[ʒwe]","🎮",["玩","演奏","打(球)"],["to play"],
      ["Les enfants jouent dans le parc.","孩子们在公园里玩。","The children play in the park."],
      ["Il joue du piano.","他弹钢琴。","He plays the piano."],
      [{fr:"jouer au football",zh:"踢足球"}],""),
    w("b1_130",L1,"gagner","v.","动词",null,"[ɡaɲe]","🏅",["赢","赚"],["to win","to earn"],
      ["Notre équipe a gagné le match.","我们队赢了比赛。","Our team won the match."],
      ["Elle gagne bien sa vie.","她收入不错。","She earns a good living."],
      [{fr:"gagner un prix",zh:"赢得奖项"}],""),
    w("b1_131",L1,"courir","v.","动词",null,"[kuʁiʁ]","🏃",["跑","奔跑"],["to run"],
      ["Il court tous les matins.","他每天早上跑步。","He runs every morning."],
      ["Ne cours pas dans les escaliers.","别在楼梯上跑。","Don't run on the stairs."],
      [{fr:"courir un marathon",zh:"跑马拉松"}],""),
    w("b1_132",L1,"nager","v.","动词",null,"[naʒe]","🏊",["游泳"],["to swim"],
      ["Elle sait nager depuis l'enfance.","她从小就会游泳。","She has been able to swim since childhood."],
      ["On va nager dans le lac.","我们去湖里游泳。","We're going to swim in the lake."],
      [{fr:"nager la brasse",zh:"蛙泳"}],""),
    w("b1_133",L1,"danser","v.","动词",null,"[dɑ̃se]","💃",["跳舞"],["to dance"],
      ["Ils dansent toute la nuit.","他们跳了一整晚舞。","They dance all night."],
      ["Tu veux danser avec moi ?","你想和我跳舞吗？","Do you want to dance with me?"],
      [{fr:"aller danser",zh:"去跳舞"}],""),
    w("b1_134",L1,"chanter","v.","动词",null,"[ʃɑ̃te]","🎤",["唱歌"],["to sing"],
      ["Elle chante très bien.","她唱歌很好听。","She sings very well."],
      ["On chante ensemble à la fête.","我们在聚会上一起唱歌。","We sing together at the party."],
      [{fr:"chanter une chanson",zh:"唱一首歌"}],""),
    w("b1_135",L1,"musique","n.f.","阴性名词","f","[myzik]","🎵",["音乐"],["music"],
      ["J'écoute de la musique classique.","我听古典音乐。","I listen to classical music."],
      ["La musique est trop forte.","音乐声太大了。","The music is too loud."],
      [{fr:"écouter de la musique",zh:"听音乐"}],""),
    w("b1_136",L1,"film","n.m.","阳性名词","m","[film]","🎬",["电影"],["film","movie"],
      ["Ce film est passionnant.","这部电影很精彩。","This film is exciting."],
      ["On regarde un film ce soir ?","今晚看电影吗？","Shall we watch a film tonight?"],
      [{fr:"un film d'action",zh:"动作片"}],""),
    w("b1_137",L1,"livre","n.m.","阳性名词","m","[livʁ]","📕",["书"],["book"],
      ["Ce livre est très intéressant.","这本书很有趣。","This book is very interesting."],
      ["J'emprunte un livre à la bibliothèque.","我从图书馆借一本书。","I borrow a book from the library."],
      [{fr:"lire un livre",zh:"读一本书"}],""),
    w("b1_138",L1,"jeu","n.m.","阳性名词","m","[ʒø]","🎲",["游戏"],["game"],
      ["Les enfants adorent ce jeu.","孩子们喜欢这个游戏。","The children love this game."],
      ["C'est à toi de jouer, c'est ton jeu.","轮到你玩了。","It's your turn to play."],
      [{fr:"un jeu de société",zh:"桌游"}],"复数为 « jeux »。"),
    w("b1_139",L1,"photo","n.f.","阴性名词","f","[fɔto]","📷",["照片"],["photo","picture"],
      ["Je prends une photo du coucher de soleil.","我拍了一张日落的照片。","I'm taking a photo of the sunset."],
      ["Montre-moi tes photos de vacances.","给我看看你的度假照片。","Show me your holiday photos."],
      [{fr:"prendre une photo",zh:"拍照"}],""),
    w("b1_140",L1,"ordinateur","n.m.","阳性名词","m","[ɔʁdinatœʁ]","💻",["电脑","计算机"],["computer"],
      ["Mon ordinateur est trop lent.","我的电脑太慢了。","My computer is too slow."],
      ["Il travaille sur son ordinateur.","他在用电脑工作。","He works on his computer."],
      [{fr:"un ordinateur portable",zh:"笔记本电脑"}],""),
    w("b1_141",L1,"téléphone","n.m.","阳性名词","m","[telefɔn]","📱",["电话","手机"],["telephone","phone"],
      ["Mon téléphone n'a plus de batterie.","我的手机没电了。","My phone has no battery left."],
      ["Il répond au téléphone.","他接电话。","He answers the phone."],
      [{fr:"un numéro de téléphone",zh:"电话号码"}],""),
    w("b1_142",L1,"internet","n.m.","阳性名词","m","[ɛ̃tɛʁnɛt]","🌐",["互联网","网络"],["internet"],
      ["Je cherche l'information sur internet.","我在网上查资料。","I look for the information on the internet."],
      ["Il n'y a pas d'internet ici.","这里没有网络。","There's no internet here."],
      [{fr:"surfer sur internet",zh:"上网"}],""),
    w("b1_143",L1,"message","n.m.","阳性名词","m","[mesaʒ]","💌",["消息","信息"],["message"],
      ["Je t'ai laissé un message.","我给你留了个消息。","I left you a message."],
      ["Il lit ses messages le matin.","他早上看消息。","He reads his messages in the morning."],
      [{fr:"envoyer un message",zh:"发消息"}],""),
    w("b1_144",L1,"appeler","v.","动词",null,"[aple]","📞",["打电话","叫","称呼"],["to call"],
      ["Je t'appelle ce soir.","我今晚给你打电话。","I'll call you tonight."],
      ["Comment t'appelles-tu ?","你叫什么名字？","What's your name?"],
      [{fr:"appeler au secours",zh:"呼救"}],""),
    w("b1_145",L1,"envoyer","v.","动词",null,"[ɑ̃vwaje]","📤",["寄","发送"],["to send"],
      ["Je vais envoyer le colis demain.","我明天寄包裹。","I'll send the parcel tomorrow."],
      ["Envoie-moi un e-mail.","给我发封邮件。","Send me an email."],
      [{fr:"envoyer une lettre",zh:"寄信"}],""),
    w("b1_146",L1,"recevoir","v.","动词",null,"[ʁəsəvwaʁ]","📥",["收到","接待"],["to receive"],
      ["J'ai reçu ton cadeau, merci !","我收到了你的礼物，谢谢！","I received your gift, thanks!"],
      ["Ils reçoivent des amis ce soir.","他们今晚招待朋友。","They're having friends over tonight."],
      [{fr:"recevoir une lettre",zh:"收到一封信"}],""),
    w("b1_147",L1,"nombre","n.m.","阳性名词","m","[nɔ̃bʁ]","🔢",["数字","数量"],["number"],
      ["Choisis un nombre entre un et dix.","在一到十之间选一个数字。","Choose a number between one and ten."],
      ["Le nombre d'élèves augmente.","学生人数在增加。","The number of pupils is increasing."],
      [{fr:"un grand nombre de",zh:"大量的"}],""),
    w("b1_148",L1,"beaucoup","adv.","副词",null,"[boku]","➕",["很多","非常"],["a lot","much"],
      ["Il travaille beaucoup.","他工作很多。","He works a lot."],
      ["Merci beaucoup pour ton aide.","非常感谢你的帮助。","Thank you very much for your help."],
      [{fr:"beaucoup de monde",zh:"很多人"}],""),
    w("b1_149",L1,"assez","adv.","副词",null,"[ase]","👌",["足够","相当"],["enough","quite"],
      ["Il y a assez de place pour tous.","有足够的地方给大家。","There's enough room for everyone."],
      ["Ce film est assez bon.","这部电影相当不错。","This film is quite good."],
      [{fr:"assez de temps",zh:"足够的时间"}],""),
    w("b1_150",L1,"famille","n.f.","阴性名词","f","[famij]","👨‍👩‍👧",["家庭","家人"],["family"],
      ["Je passe le week-end en famille.","我和家人一起过周末。","I spend the weekend with my family."],
      ["Sa famille habite loin.","他的家人住得很远。","His family lives far away."],
      [{fr:"une famille nombreuse",zh:"大家庭"}],""),
    w("b1_151",L1,"parent","n.m.","阳性名词","m","[paʁɑ̃]","👪",["父母","亲戚"],["parent","relative"],
      ["Mes parents habitent à Nice.","我父母住在尼斯。","My parents live in Nice."],
      ["Nous avons de la famille et des parents en Italie.","我们在意大利有亲戚。","We have relatives in Italy."],
      [{fr:"les parents d'élèves",zh:"学生家长"}],""),
    w("b1_152",L1,"enfant","n.m.","阳性名词","m","[ɑ̃fɑ̃]","🧒",["孩子","儿童"],["child"],
      ["Ils ont trois enfants.","他们有三个孩子。","They have three children."],
      ["Cet enfant est très sage.","这个孩子很乖。","This child is very well-behaved."],
      [{fr:"un jeune enfant",zh:"幼儿"}],"阴阳性同形，视语境定冠词。"),
    w("b1_153",L1,"ami","n.m.","阳性名词","m","[ami]","🧑‍🤝‍🧑",["朋友"],["friend"],
      ["C'est mon meilleur ami.","这是我最好的朋友。","This is my best friend."],
      ["Elle a beaucoup d'amis.","她有很多朋友。","She has many friends."],
      [{fr:"un ami d'enfance",zh:"儿时好友"}],"阴性形式为 « amie »。"),
    w("b1_154",L1,"vie","n.f.","阴性名词","f","[vi]","🌱",["生活","生命"],["life"],
      ["La vie est belle.","生活是美好的。","Life is beautiful."],
      ["Il a changé de vie.","他改变了自己的生活。","He changed his life."],
      [{fr:"gagner sa vie",zh:"谋生"}],""),
    w("b1_155",L1,"monde","n.m.","阳性名词","m","[mɔ̃d]","🌍",["世界","人们"],["world","people"],
      ["Il veut voyager dans le monde entier.","他想周游世界。","He wants to travel the whole world."],
      ["Il y a beaucoup de monde ici.","这里有很多人。","There are a lot of people here."],
      [{fr:"tout le monde",zh:"所有人"}],""),
    w("b1_156",L1,"histoire","n.f.","阴性名词","f","[istwaʁ]","📜",["故事","历史"],["story","history"],
      ["Raconte-moi une histoire.","给我讲个故事。","Tell me a story."],
      ["Il étudie l'histoire de France.","他研究法国历史。","He studies the history of France."],
      [{fr:"une belle histoire",zh:"一个美好的故事"}],"")
    ,
    w("b1_157",L1,"commencer","v.","动词",null,"[kɔmɑ̃se]","▶️",["开始"],["to begin","to start"],
      ["Le cours commence à neuf heures.","课程九点开始。","The class begins at nine."],
      ["Il commence à pleuvoir.","开始下雨了。","It's starting to rain."],
      [{fr:"commencer à faire",zh:"开始做某事"}],""),
    w("b1_158",L1,"finir","v.","动词",null,"[finiʁ]","🏁",["结束","完成"],["to finish"],
      ["J'ai fini mes devoirs.","我完成了作业。","I've finished my homework."],
      ["Le film finit bien.","电影结局圆满。","The film ends well."],
      [{fr:"finir un travail",zh:"完成工作"}],""),
    w("b1_159",L1,"continuer","v.","动词",null,"[kɔ̃tinɥe]","➡️",["继续"],["to continue"],
      ["Continue, tu y es presque !","继续，你快成功了！","Keep going, you're almost there!"],
      ["Il continue ses études à Paris.","他在巴黎继续学业。","He continues his studies in Paris."],
      [{fr:"continuer à faire",zh:"继续做"}],""),
    w("b1_160",L1,"donner","v.","动词",null,"[dɔne]","🤲",["给","给予"],["to give"],
      ["Donne-moi ton adresse.","把你的地址给我。","Give me your address."],
      ["Elle donne des cours de piano.","她教钢琴课。","She gives piano lessons."],
      [{fr:"donner un coup de main",zh:"帮个忙"}],""),
    w("b1_161",L1,"prendre","v.","动词",null,"[pʁɑ̃dʁ]","🫳",["拿","取","乘坐"],["to take"],
      ["Je prends le métro tous les jours.","我每天坐地铁。","I take the metro every day."],
      ["Prends un parapluie, il pleut.","带把伞，在下雨。","Take an umbrella, it's raining."],
      [{fr:"prendre une décision",zh:"做决定"}],""),
    w("b1_162",L1,"mettre","v.","动词",null,"[mɛtʁ]","📥",["放","放置","穿"],["to put","to put on"],
      ["Mets tes clés sur la table.","把钥匙放桌上。","Put your keys on the table."],
      ["Je mets un pull, il fait froid.","天冷，我加件毛衣。","I'm putting on a jumper, it's cold."],
      [{fr:"mettre de côté",zh:"存起来"}],""),
    w("b1_163",L1,"ouvrir","v.","动词",null,"[uvʁiʁ]","🔓",["打开","开"],["to open"],
      ["Ouvre la boîte doucement.","轻轻打开盒子。","Open the box gently."],
      ["Le magasin ouvre à dix heures.","商店十点开门。","The shop opens at ten."],
      [{fr:"ouvrir la porte",zh:"开门"}],""),
    w("b1_164",L1,"fermer","v.","动词",null,"[fɛʁme]","🔒",["关","关闭"],["to close","to shut"],
      ["Ferme la fenêtre, s'il te plaît.","请关上窗户。","Close the window, please."],
      ["La banque ferme à midi.","银行中午关门。","The bank closes at noon."],
      [{fr:"fermer à clé",zh:"锁上"}],""),
    w("b1_165",L1,"monter","v.","动词",null,"[mɔ̃te]","⬆️",["上","上升","登"],["to go up","to climb"],
      ["Monte dans la voiture.","上车吧。","Get in the car."],
      ["Les prix montent chaque année.","价格每年上涨。","Prices go up every year."],
      [{fr:"monter l'escalier",zh:"上楼梯"}],""),
    w("b1_166",L1,"descendre","v.","动词",null,"[desɑ̃dʁ]","⬇️",["下","下来","下车"],["to go down","to get off"],
      ["Je descends au prochain arrêt.","我在下一站下车。","I'm getting off at the next stop."],
      ["Descends vite, on t'attend.","快下来，我们等你。","Come down quickly, we're waiting."],
      [{fr:"descendre du bus",zh:"下公交"}],""),
    w("b1_167",L1,"tomber","v.","动词",null,"[tɔ̃be]","🍂",["跌倒","掉落"],["to fall"],
      ["Attention, tu vas tomber !","小心，你要摔倒了！","Watch out, you're going to fall!"],
      ["Les feuilles tombent en automne.","秋天叶子落下。","Leaves fall in autumn."],
      [{fr:"tomber malade",zh:"生病"}],""),
    w("b1_168",L1,"aider","v.","动词",null,"[ede]","🆘",["帮助"],["to help"],
      ["Peux-tu m'aider à porter ça ?","你能帮我拿这个吗？","Can you help me carry this?"],
      ["Elle aide les personnes âgées.","她帮助老年人。","She helps elderly people."],
      [{fr:"aider quelqu'un",zh:"帮助某人"}],""),
    w("b1_169",L1,"montrer","v.","动词",null,"[mɔ̃tʁe]","👉",["展示","给…看","指"],["to show"],
      ["Montre-moi le chemin.","给我指路。","Show me the way."],
      ["Il montre ses dessins à la classe.","他向全班展示他的画。","He shows his drawings to the class."],
      [{fr:"montrer du doigt",zh:"用手指"}],""),
    w("b1_170",L1,"utiliser","v.","动词",null,"[ytilize]","🛠️",["使用","利用"],["to use"],
      ["J'utilise mon vélo pour aller au travail.","我骑自行车上班。","I use my bike to get to work."],
      ["On utilise cette salle pour les réunions.","这个房间用于开会。","We use this room for meetings."],
      [{fr:"utiliser un outil",zh:"使用工具"}],""),
    w("b1_171",L1,"changer","v.","动词",null,"[ʃɑ̃ʒe]","🔄",["改变","更换"],["to change"],
      ["Il a changé d'avis.","他改变了主意。","He changed his mind."],
      ["Je dois changer de train à Lyon.","我得在里昂换乘火车。","I have to change trains in Lyon."],
      [{fr:"changer d'avis",zh:"改变主意"}],""),
    w("b1_172",L1,"choisir","v.","动词",null,"[ʃwaziʁ]","✅",["选择","挑选"],["to choose"],
      ["Choisis la couleur que tu préfères.","选你喜欢的颜色。","Choose the colour you prefer."],
      ["Il est difficile de choisir.","很难做选择。","It's hard to choose."],
      [{fr:"choisir entre deux",zh:"在两者间选择"}],""),
    w("b1_173",L1,"essayer","v.","动词",null,"[eseje]","🧪",["尝试","试"],["to try"],
      ["Essaie encore une fois.","再试一次。","Try one more time."],
      ["Je voudrais essayer ce manteau.","我想试穿这件外套。","I'd like to try on this coat."],
      [{fr:"essayer de faire",zh:"设法做"}],""),
    w("b1_174",L1,"réponse","n.f.","阴性名词","f","[ʁepɔ̃s]","💬",["回答","答复"],["answer","reply"],
      ["Ta réponse est correcte.","你的回答是对的。","Your answer is correct."],
      ["J'attends ta réponse.","我等你的答复。","I'm waiting for your reply."],
      [{fr:"donner une réponse",zh:"给出答复"}],""),
    w("b1_175",L1,"vrai","adj.","形容词",null,"[vʁɛ]","✔️",["真的","真实的"],["true","real"],
      ["C'est une histoire vraie.","这是个真实的故事。","It's a true story."],
      ["Est-ce vrai ou faux ?","这是真的还是假的？","Is it true or false?"],
      [{fr:"un vrai ami",zh:"真正的朋友"}],"阴性形式为 « vraie »。"),
    w("b1_176",L1,"faux","adj.","形容词",null,"[fo]","✖️",["假的","错误的"],["false","wrong"],
      ["Cette information est fausse.","这条信息是假的。","This information is false."],
      ["Il a donné une fausse adresse.","他给了一个假地址。","He gave a false address."],
      [{fr:"une fausse note",zh:"走调"}],"阴性形式为 « fausse »。"),
    w("b1_177",L1,"facile","adj.","形容词",null,"[fasil]","🟢",["容易的","简单的"],["easy"],
      ["Cet exercice est facile.","这道练习很简单。","This exercise is easy."],
      ["Ce n'est pas facile à dire.","这不容易说出口。","It's not easy to say."],
      [{fr:"facile à faire",zh:"容易做"}],""),
    w("b1_178",L1,"difficile","adj.","形容词",null,"[difisil]","🔴",["困难的","难的"],["difficult","hard"],
      ["La question est difficile.","这个问题很难。","The question is difficult."],
      ["Il traverse une période difficile.","他正经历一段艰难时期。","He's going through a difficult time."],
      [{fr:"un choix difficile",zh:"艰难的选择"}],""),
    w("b1_179",L1,"important","adj.","形容词",null,"[ɛ̃pɔʁtɑ̃]","❗",["重要的"],["important"],
      ["C'est une décision importante.","这是一个重要的决定。","It's an important decision."],
      ["Il est important de bien dormir.","好好睡觉很重要。","It's important to sleep well."],
      [{fr:"un rôle important",zh:"重要的角色"}],"阴性形式为 « importante »。"),
    w("b1_180",L1,"nouveau","adj.","形容词",null,"[nuvo]","🆕",["新的"],["new"],
      ["J'ai un nouveau téléphone.","我有个新手机。","I have a new phone."],
      ["Une nouvelle boulangerie a ouvert.","一家新面包店开张了。","A new bakery has opened."],
      [{fr:"le nouvel an",zh:"新年"}],"« nouvel » 用于元音开头的阳性名词前；阴性为 « nouvelle »。"),
    w("b1_181",L1,"vieux","adj.","形容词",null,"[vjø]","👴",["老的","旧的"],["old"],
      ["C'est un vieux château.","这是一座古老的城堡。","It's an old castle."],
      ["Il conduit une vieille voiture.","他开着一辆旧车。","He drives an old car."],
      [{fr:"un vieil ami",zh:"老朋友"}],"« vieil » 用于元音开头的阳性名词前；阴性为 « vieille »。"),
    w("b1_182",L1,"jeune","adj.","形容词",null,"[ʒœn]","🧒",["年轻的"],["young"],
      ["Elle est encore très jeune.","她还很年轻。","She's still very young."],
      ["Les jeunes gens aiment sortir.","年轻人喜欢外出。","Young people like to go out."],
      [{fr:"un jeune homme",zh:"年轻男子"}],""),
    w("b1_183",L1,"grand","adj.","形容词",null,"[ɡʁɑ̃]","📏",["大的","高的"],["big","tall"],
      ["Ils habitent une grande maison.","他们住在一座大房子里。","They live in a big house."],
      ["Mon frère est très grand.","我哥哥个子很高。","My brother is very tall."],
      [{fr:"une grande ville",zh:"大城市"}],"阴性形式为 « grande »。"),
    w("b1_184",L1,"petit","adj.","形容词",null,"[pəti]","🤏",["小的"],["small","little"],
      ["Ils ont un petit chien.","他们有一只小狗。","They have a little dog."],
      ["Attends une petite minute.","稍等一小会儿。","Wait a little minute."],
      [{fr:"un petit peu",zh:"一点点"}],"阴性形式为 « petite »。"),
    w("b1_185",L1,"beau","adj.","形容词",null,"[bo]","🌺",["美的","漂亮的"],["beautiful","fine"],
      ["Quel beau paysage !","多美的风景啊！","What a beautiful landscape!"],
      ["Il fait beau aujourd'hui.","今天天气很好。","The weather is fine today."],
      [{fr:"un bel homme",zh:"英俊的男子"}],"« bel » 用于元音开头的阳性名词前；阴性为 « belle »。"),
    w("b1_186",L1,"joli","adj.","形容词",null,"[ʒɔli]","🌼",["漂亮的","好看的"],["pretty","nice"],
      ["Elle porte une jolie robe.","她穿着一条漂亮的裙子。","She's wearing a pretty dress."],
      ["C'est un joli petit village.","这是个漂亮的小村庄。","It's a pretty little village."],
      [{fr:"un joli cadeau",zh:"精美的礼物"}],"阴性形式为 « jolie »。"),
    w("b1_187",L1,"propre","adj.","形容词",null,"[pʁɔpʁ]","🧼",["干净的","自己的"],["clean","own"],
      ["Ta chambre est propre maintenant.","你的房间现在干净了。","Your room is clean now."],
      ["Il a sa propre entreprise.","他有自己的公司。","He has his own company."],
      [{fr:"les mains propres",zh:"干净的手"}],""),
    w("b1_188",L1,"sale","adj.","形容词",null,"[sal]","🧹",["脏的"],["dirty"],
      ["Tes chaussures sont sales.","你的鞋子脏了。","Your shoes are dirty."],
      ["L'eau de la rivière est sale.","河水很脏。","The river water is dirty."],
      [{fr:"du linge sale",zh:"脏衣服"}],""),
    w("b1_189",L1,"plein","adj.","形容词",null,"[plɛ̃]","🔵",["满的","充满的"],["full"],
      ["Le verre est plein.","杯子满了。","The glass is full."],
      ["La salle est pleine de monde.","大厅里挤满了人。","The room is full of people."],
      [{fr:"en plein air",zh:"在户外"}],"阴性形式为 « pleine »。"),
    w("b1_190",L1,"vide","adj.","形容词",null,"[vid]","⚪",["空的"],["empty"],
      ["La bouteille est vide.","瓶子空了。","The bottle is empty."],
      ["La rue est vide la nuit.","夜里街道空无一人。","The street is empty at night."],
      [{fr:"un ventre vide",zh:"空肚子"}],""),
    w("b1_191",L1,"rapide","adj.","形容词",null,"[ʁapid]","⚡",["快的","迅速的"],["fast","quick"],
      ["Ce train est très rapide.","这趟火车很快。","This train is very fast."],
      ["Il a donné une réponse rapide.","他很快就回答了。","He gave a quick answer."],
      [{fr:"un repas rapide",zh:"快餐"}],""),
    w("b1_192",L1,"lent","adj.","形容词",null,"[lɑ̃]","🐌",["慢的","缓慢的"],["slow"],
      ["Ma connexion est trop lente.","我的网络太慢了。","My connection is too slow."],
      ["Il marche d'un pas lent.","他步伐缓慢。","He walks with a slow step."],
      [{fr:"un rythme lent",zh:"缓慢的节奏"}],"阴性形式为 « lente »。"),
    w("b1_193",L1,"fort","adj.","形容词",null,"[fɔʁ]","💪",["强的","大声的"],["strong","loud"],
      ["Il est fort en mathématiques.","他数学很好。","He's strong in maths."],
      ["Le bruit est trop fort.","声音太大了。","The noise is too loud."],
      [{fr:"parler fort",zh:"大声说话"}],"阴性形式为 « forte »。"),
    w("b1_194",L1,"faible","adj.","形容词",null,"[fɛbl]","🍃",["弱的","微弱的"],["weak"],
      ["Le signal est trop faible.","信号太弱了。","The signal is too weak."],
      ["Il se sent faible après sa maladie.","病后他感到虚弱。","He feels weak after his illness."],
      [{fr:"un point faible",zh:"弱点"}],""),
    w("b1_195",L1,"possible","adj.","形容词",null,"[pɔsibl]","🔓",["可能的"],["possible"],
      ["Est-ce possible de changer la date ?","有可能改日期吗？","Is it possible to change the date?"],
      ["Je viendrai dès que possible.","我会尽快来。","I'll come as soon as possible."],
      [{fr:"si possible",zh:"如果可能的话"}],""),
    w("b1_196",L1,"nécessaire","adj.","形容词",null,"[neseseʁ]","🧷",["必要的","必需的"],["necessary"],
      ["Il est nécessaire de réserver.","有必要预订。","It's necessary to book."],
      ["Prends tout le matériel nécessaire.","带上所有必需的材料。","Take all the necessary equipment."],
      [{fr:"si nécessaire",zh:"如有必要"}],""),
    w("b1_197",L1,"ensemble","adv.","副词",null,"[ɑ̃sɑ̃bl]","🤝",["一起"],["together"],
      ["Nous travaillons ensemble.","我们一起工作。","We work together."],
      ["Ils partent en vacances ensemble.","他们一起去度假。","They go on holiday together."],
      [{fr:"tous ensemble",zh:"大家一起"}],""),
    w("b1_198",L1,"souvent","adv.","副词",null,"[suvɑ̃]","🔁",["经常","常常"],["often"],
      ["Je vais souvent au cinéma.","我经常去电影院。","I often go to the cinema."],
      ["Il pleut souvent en automne.","秋天经常下雨。","It often rains in autumn."],
      [{fr:"le plus souvent",zh:"多数情况下"}],""),
    w("b1_199",L1,"toujours","adv.","副词",null,"[tuʒuʁ]","♾️",["总是","一直"],["always","still"],
      ["Elle est toujours en retard.","她总是迟到。","She's always late."],
      ["Il habite toujours ici.","他仍然住在这里。","He still lives here."],
      [{fr:"pour toujours",zh:"永远"}],""),
    w("b1_200",L1,"jamais","adv.","副词",null,"[ʒamɛ]","🚫",["从不","永不"],["never"],
      ["Je ne mens jamais.","我从不撒谎。","I never lie."],
      ["Il n'est jamais allé à Paris.","他从没去过巴黎。","He has never been to Paris."],
      [{fr:"ne… jamais",zh:"从不"}],"")
    /* ===== EXPANSION CURÉE (objectif progressif 200→1000 / niveau) ===== */
  ];
  window.VOCAB_DATA={
    levels:[L1,L2,L3,L4],
    levelLabel:{DELF_B1:"DELF B1",DELF_B2:"DELF B2",DALF_C1:"DALF C1",DALF_C2:"DALF C2"},
    levelZh:{DELF_B1:"B1 日常",DELF_B2:"B2 社会",DALF_C1:"C1 高级",DALF_C2:"C2 精通"},
    words:WORDS
  };
})();
